/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.enums;


import com.ethercis.jooq.pg.Ehr;

import javax.annotation.Generated;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EntryType implements EnumType {

	section("section"),

	care_entry("care_entry"),

	admin("admin"),

	proxy("proxy");

	private final String literal;

	private EntryType(String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return Ehr.EHR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		return "entry_type";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getLiteral() {
		return literal;
	}
}
