/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables.records;


import com.ethercis.jooq.pg.tables.CompExpand;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompExpandRecord extends TableRecordImpl<CompExpandRecord> {

	private static final long serialVersionUID = -1327016398;

	/**
	 * Setter for <code>ehr.comp_expand.ehr_id</code>.
	 */
	public void setEhrId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.ehr_id</code>.
	 */
	public UUID getEhrId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.comp_expand.subject_externalref_id_value</code>.
	 */
	public void setSubjectExternalrefIdValue(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.subject_externalref_id_value</code>.
	 */
	public String getSubjectExternalrefIdValue() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ehr.comp_expand.subject_externalref_id_namespace</code>.
	 */
	public void setSubjectExternalrefIdNamespace(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.subject_externalref_id_namespace</code>.
	 */
	public String getSubjectExternalrefIdNamespace() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ehr.comp_expand.composition_id</code>.
	 */
	public void setCompositionId(UUID value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.composition_id</code>.
	 */
	public UUID getCompositionId() {
		return (UUID) getValue(3);
	}

	/**
	 * Setter for <code>ehr.comp_expand.template_id</code>.
	 */
	public void setTemplateId(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.template_id</code>.
	 */
	public String getTemplateId() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.comp_expand.archetype_id</code>.
	 */
	public void setArchetypeId(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.archetype_id</code>.
	 */
	public String getArchetypeId() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ehr.comp_expand.entry</code>.
	 */
	public void setEntry(Object value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.entry</code>.
	 */
	public Object getEntry() {
		return (Object) getValue(6);
	}

	/**
	 * Setter for <code>ehr.comp_expand.composition_name</code>.
	 */
	public void setCompositionName(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.composition_name</code>.
	 */
	public String getCompositionName() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>ehr.comp_expand.language</code>.
	 */
	public void setLanguage(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.language</code>.
	 */
	public String getLanguage() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>ehr.comp_expand.territory</code>.
	 */
	public void setTerritory(Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.territory</code>.
	 */
	public Integer getTerritory() {
		return (Integer) getValue(9);
	}

	/**
	 * Setter for <code>ehr.comp_expand.start_time</code>.
	 */
	public void setStartTime(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.start_time</code>.
	 */
	public Timestamp getStartTime() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>ehr.comp_expand.start_time_tzid</code>.
	 */
	public void setStartTimeTzid(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.start_time_tzid</code>.
	 */
	public String getStartTimeTzid() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>ehr.comp_expand.end_time</code>.
	 */
	public void setEndTime(Timestamp value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.end_time</code>.
	 */
	public Timestamp getEndTime() {
		return (Timestamp) getValue(12);
	}

	/**
	 * Setter for <code>ehr.comp_expand.end_time_tzid</code>.
	 */
	public void setEndTimeTzid(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.end_time_tzid</code>.
	 */
	public String getEndTimeTzid() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>ehr.comp_expand.other_context</code>.
	 */
	public void setOtherContext(Object value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.other_context</code>.
	 */
	public Object getOtherContext() {
		return (Object) getValue(14);
	}

	/**
	 * Setter for <code>ehr.comp_expand.ctx_location</code>.
	 */
	public void setCtxLocation(String value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.ctx_location</code>.
	 */
	public String getCtxLocation() {
		return (String) getValue(15);
	}

	/**
	 * Setter for <code>ehr.comp_expand.facility_name</code>.
	 */
	public void setFacilityName(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.facility_name</code>.
	 */
	public String getFacilityName() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>ehr.comp_expand.facility_ref</code>.
	 */
	public void setFacilityRef(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.facility_ref</code>.
	 */
	public String getFacilityRef() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>ehr.comp_expand.facility_scheme</code>.
	 */
	public void setFacilityScheme(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.facility_scheme</code>.
	 */
	public String getFacilityScheme() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>ehr.comp_expand.facility_namespace</code>.
	 */
	public void setFacilityNamespace(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.facility_namespace</code>.
	 */
	public String getFacilityNamespace() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>ehr.comp_expand.facility_type</code>.
	 */
	public void setFacilityType(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.facility_type</code>.
	 */
	public String getFacilityType() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>ehr.comp_expand.composer_name</code>.
	 */
	public void setComposerName(String value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.composer_name</code>.
	 */
	public String getComposerName() {
		return (String) getValue(21);
	}

	/**
	 * Setter for <code>ehr.comp_expand.composer_ref</code>.
	 */
	public void setComposerRef(String value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.composer_ref</code>.
	 */
	public String getComposerRef() {
		return (String) getValue(22);
	}

	/**
	 * Setter for <code>ehr.comp_expand.composer_scheme</code>.
	 */
	public void setComposerScheme(String value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.composer_scheme</code>.
	 */
	public String getComposerScheme() {
		return (String) getValue(23);
	}

	/**
	 * Setter for <code>ehr.comp_expand.composer_namespace</code>.
	 */
	public void setComposerNamespace(String value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.composer_namespace</code>.
	 */
	public String getComposerNamespace() {
		return (String) getValue(24);
	}

	/**
	 * Setter for <code>ehr.comp_expand.composer_type</code>.
	 */
	public void setComposerType(String value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>ehr.comp_expand.composer_type</code>.
	 */
	public String getComposerType() {
		return (String) getValue(25);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CompExpandRecord
	 */
	public CompExpandRecord() {
		super(CompExpand.COMP_EXPAND);
	}

	/**
	 * Create a detached, initialised CompExpandRecord
	 */
	public CompExpandRecord(UUID ehrId, String subjectExternalrefIdValue, String subjectExternalrefIdNamespace, UUID compositionId, String templateId, String archetypeId, Object entry, String compositionName, String language, Integer territory, Timestamp startTime, String startTimeTzid, Timestamp endTime, String endTimeTzid, Object otherContext, String ctxLocation, String facilityName, String facilityRef, String facilityScheme, String facilityNamespace, String facilityType, String composerName, String composerRef, String composerScheme, String composerNamespace, String composerType) {
		super(CompExpand.COMP_EXPAND);

		setValue(0, ehrId);
		setValue(1, subjectExternalrefIdValue);
		setValue(2, subjectExternalrefIdNamespace);
		setValue(3, compositionId);
		setValue(4, templateId);
		setValue(5, archetypeId);
		setValue(6, entry);
		setValue(7, compositionName);
		setValue(8, language);
		setValue(9, territory);
		setValue(10, startTime);
		setValue(11, startTimeTzid);
		setValue(12, endTime);
		setValue(13, endTimeTzid);
		setValue(14, otherContext);
		setValue(15, ctxLocation);
		setValue(16, facilityName);
		setValue(17, facilityRef);
		setValue(18, facilityScheme);
		setValue(19, facilityNamespace);
		setValue(20, facilityType);
		setValue(21, composerName);
		setValue(22, composerRef);
		setValue(23, composerScheme);
		setValue(24, composerNamespace);
		setValue(25, composerType);
	}
}
