/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables.records;


import com.ethercis.jooq.pg.tables.SessionLog;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionLogRecord extends UpdatableRecordImpl<SessionLogRecord> implements Record7<UUID, String, String, String, String, Timestamp, String> {

	private static final long serialVersionUID = 1681287413;

	/**
	 * Setter for <code>ehr.session_log.id</code>.
	 */
	public void setId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.session_log.id</code>.
	 */
	public UUID getId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.session_log.subject_id</code>.
	 */
	public void setSubjectId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.session_log.subject_id</code>.
	 */
	public String getSubjectId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>ehr.session_log.node_id</code>.
	 */
	public void setNodeId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.session_log.node_id</code>.
	 */
	public String getNodeId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>ehr.session_log.session_id</code>.
	 */
	public void setSessionId(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.session_log.session_id</code>.
	 */
	public String getSessionId() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>ehr.session_log.session_name</code>.
	 */
	public void setSessionName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.session_log.session_name</code>.
	 */
	public String getSessionName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.session_log.session_time</code>.
	 */
	public void setSessionTime(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.session_log.session_time</code>.
	 */
	public Timestamp getSessionTime() {
		return (Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>ehr.session_log.ip_address</code>.
	 */
	public void setIpAddress(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.session_log.ip_address</code>.
	 */
	public String getIpAddress() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UUID> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<UUID, String, String, String, String, Timestamp, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<UUID, String, String, String, String, Timestamp, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return SessionLog.SESSION_LOG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return SessionLog.SESSION_LOG.SUBJECT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SessionLog.SESSION_LOG.NODE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return SessionLog.SESSION_LOG.SESSION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return SessionLog.SESSION_LOG.SESSION_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return SessionLog.SESSION_LOG.SESSION_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return SessionLog.SESSION_LOG.IP_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getSubjectId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getNodeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getSessionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getSessionName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getSessionTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getIpAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLogRecord value1(UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLogRecord value2(String value) {
		setSubjectId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLogRecord value3(String value) {
		setNodeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLogRecord value4(String value) {
		setSessionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLogRecord value5(String value) {
		setSessionName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLogRecord value6(Timestamp value) {
		setSessionTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLogRecord value7(String value) {
		setIpAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLogRecord values(UUID value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SessionLogRecord
	 */
	public SessionLogRecord() {
		super(SessionLog.SESSION_LOG);
	}

	/**
	 * Create a detached, initialised SessionLogRecord
	 */
	public SessionLogRecord(UUID id, String subjectId, String nodeId, String sessionId, String sessionName, Timestamp sessionTime, String ipAddress) {
		super(SessionLog.SESSION_LOG);

		setValue(0, id);
		setValue(1, subjectId);
		setValue(2, nodeId);
		setValue(3, sessionId);
		setValue(4, sessionName);
		setValue(5, sessionTime);
		setValue(6, ipAddress);
	}
}
