/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables.records;


import com.ethercis.jooq.pg.tables.StatusDetails;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusDetailsRecord extends TableRecordImpl<StatusDetailsRecord> implements Record8<UUID, Boolean, Boolean, Object, String, String, String, String> {

	private static final long serialVersionUID = 109877991;

	/**
	 * Setter for <code>ehr.status_details.ehr_id</code>.
	 */
	public void setEhrId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.status_details.ehr_id</code>.
	 */
	public UUID getEhrId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.status_details.is_modifiable</code>.
	 */
	public void setIsModifiable(Boolean value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.status_details.is_modifiable</code>.
	 */
	public Boolean getIsModifiable() {
		return (Boolean) getValue(1);
	}

	/**
	 * Setter for <code>ehr.status_details.is_queryable</code>.
	 */
	public void setIsQueryable(Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.status_details.is_queryable</code>.
	 */
	public Boolean getIsQueryable() {
		return (Boolean) getValue(2);
	}

	/**
	 * Setter for <code>ehr.status_details.other_details</code>.
	 */
	public void setOtherDetails(Object value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.status_details.other_details</code>.
	 */
	public Object getOtherDetails() {
		return (Object) getValue(3);
	}

	/**
	 * Setter for <code>ehr.status_details.party_name</code>.
	 */
	public void setPartyName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.status_details.party_name</code>.
	 */
	public String getPartyName() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.status_details.party_ref_namespace</code>.
	 */
	public void setPartyRefNamespace(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.status_details.party_ref_namespace</code>.
	 */
	public String getPartyRefNamespace() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>ehr.status_details.party_ref_scheme</code>.
	 */
	public void setPartyRefScheme(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.status_details.party_ref_scheme</code>.
	 */
	public String getPartyRefScheme() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ehr.status_details.party_ref_type</code>.
	 */
	public void setPartyRefType(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.status_details.party_ref_type</code>.
	 */
	public String getPartyRefType() {
		return (String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<UUID, Boolean, Boolean, Object, String, String, String, String> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<UUID, Boolean, Boolean, Object, String, String, String, String> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return StatusDetails.STATUS_DETAILS.EHR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field2() {
		return StatusDetails.STATUS_DETAILS.IS_MODIFIABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field3() {
		return StatusDetails.STATUS_DETAILS.IS_QUERYABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field4() {
		return StatusDetails.STATUS_DETAILS.OTHER_DETAILS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return StatusDetails.STATUS_DETAILS.PARTY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return StatusDetails.STATUS_DETAILS.PARTY_REF_NAMESPACE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return StatusDetails.STATUS_DETAILS.PARTY_REF_SCHEME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return StatusDetails.STATUS_DETAILS.PARTY_REF_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getEhrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value2() {
		return getIsModifiable();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value3() {
		return getIsQueryable();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value4() {
		return getOtherDetails();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPartyName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getPartyRefNamespace();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getPartyRefScheme();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getPartyRefType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord value1(UUID value) {
		setEhrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord value2(Boolean value) {
		setIsModifiable(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord value3(Boolean value) {
		setIsQueryable(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord value4(Object value) {
		setOtherDetails(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord value5(String value) {
		setPartyName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord value6(String value) {
		setPartyRefNamespace(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord value7(String value) {
		setPartyRefScheme(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord value8(String value) {
		setPartyRefType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetailsRecord values(UUID value1, Boolean value2, Boolean value3, Object value4, String value5, String value6, String value7, String value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StatusDetailsRecord
	 */
	public StatusDetailsRecord() {
		super(StatusDetails.STATUS_DETAILS);
	}

	/**
	 * Create a detached, initialised StatusDetailsRecord
	 */
	public StatusDetailsRecord(UUID ehrId, Boolean isModifiable, Boolean isQueryable, Object otherDetails, String partyName, String partyRefNamespace, String partyRefScheme, String partyRefType) {
		super(StatusDetails.STATUS_DETAILS);

		setValue(0, ehrId);
		setValue(1, isModifiable);
		setValue(2, isQueryable);
		setValue(3, otherDetails);
		setValue(4, partyName);
		setValue(5, partyRefNamespace);
		setValue(6, partyRefScheme);
		setValue(7, partyRefType);
	}
}
