/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables.records;


import com.ethercis.jooq.pg.tables.TemplateMeta;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateMetaRecord extends TableRecordImpl<TemplateMetaRecord> implements Record2<String, String[]> {

	private static final long serialVersionUID = -1037068629;

	/**
	 * Setter for <code>ehr.template_meta.template_id</code>.
	 */
	public void setTemplateId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.template_meta.template_id</code>.
	 */
	public String getTemplateId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ehr.template_meta.array_path</code>.
	 */
	public void setArrayPath(String[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.template_meta.array_path</code>.
	 */
	public String[] getArrayPath() {
		return (String[]) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String[]> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, String[]> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TemplateMeta.TEMPLATE_META.TEMPLATE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String[]> field2() {
		return TemplateMeta.TEMPLATE_META.ARRAY_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getTemplateId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String[] value2() {
		return getArrayPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TemplateMetaRecord value1(String value) {
		setTemplateId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TemplateMetaRecord value2(String[] value) {
		setArrayPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TemplateMetaRecord values(String value1, String[] value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TemplateMetaRecord
	 */
	public TemplateMetaRecord() {
		super(TemplateMeta.TEMPLATE_META);
	}

	/**
	 * Create a detached, initialised TemplateMetaRecord
	 */
	public TemplateMetaRecord(String templateId, String[] arrayPath) {
		super(TemplateMeta.TEMPLATE_META);

		setValue(0, templateId);
		setValue(1, arrayPath);
	}
}
