/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables.records;


import com.ethercis.jooq.pg.tables.TemplateHeadingXref;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateHeadingXrefRecord extends TableRecordImpl<TemplateHeadingXrefRecord> implements Record2<String, UUID> {

	private static final long serialVersionUID = -873596721;

	/**
	 * Setter for <code>ehr.template_heading_xref.heading_code</code>.
	 */
	public void setHeadingCode(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.template_heading_xref.heading_code</code>.
	 */
	public String getHeadingCode() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>ehr.template_heading_xref.template_id</code>.
	 */
	public void setTemplateId(UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.template_heading_xref.template_id</code>.
	 */
	public UUID getTemplateId() {
		return (UUID) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, UUID> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, UUID> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TemplateHeadingXref.TEMPLATE_HEADING_XREF.HEADING_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return TemplateHeadingXref.TEMPLATE_HEADING_XREF.TEMPLATE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getHeadingCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getTemplateId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TemplateHeadingXrefRecord value1(String value) {
		setHeadingCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TemplateHeadingXrefRecord value2(UUID value) {
		setTemplateId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TemplateHeadingXrefRecord values(String value1, UUID value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TemplateHeadingXrefRecord
	 */
	public TemplateHeadingXrefRecord() {
		super(TemplateHeadingXref.TEMPLATE_HEADING_XREF);
	}

	/**
	 * Create a detached, initialised TemplateHeadingXrefRecord
	 */
	public TemplateHeadingXrefRecord(String headingCode, UUID templateId) {
		super(TemplateHeadingXref.TEMPLATE_HEADING_XREF);

		setValue(0, headingCode);
		setValue(1, templateId);
	}
}
