/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EntryType implements org.jooq.EnumType {

	section("section"),

	care_entry("care_entry"),

	admin("admin"),

	proxy("proxy");

	private final java.lang.String literal;

	private EntryType(java.lang.String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Schema getSchema() {
		return com.ethercis.dao.jooq.Ehr.EHR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getName() {
		return "entry_type";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
