/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables.records;


import com.ethercis.jooq.pg.enums.EntryType;
import com.ethercis.jooq.pg.tables.EntryHistory;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntryHistoryRecord extends TableRecordImpl<EntryHistoryRecord> implements Record11<UUID, UUID, Integer, EntryType, String, UUID, String, UUID, Object, Timestamp, Object> {

	private static final long serialVersionUID = 253740216;

	/**
	 * Setter for <code>ehr.entry_history.id</code>.
	 */
	public void setId(UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.id</code>.
	 */
	public UUID getId() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.entry_history.composition_id</code>.
	 */
	public void setCompositionId(UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.composition_id</code>.
	 */
	public UUID getCompositionId() {
		return (UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.entry_history.sequence</code>.
	 */
	public void setSequence(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.sequence</code>.
	 */
	public Integer getSequence() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>ehr.entry_history.item_type</code>.
	 */
	public void setItemType(EntryType value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.item_type</code>.
	 */
	public EntryType getItemType() {
		return (EntryType) getValue(3);
	}

	/**
	 * Setter for <code>ehr.entry_history.template_id</code>.
	 */
	public void setTemplateId(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.template_id</code>.
	 */
	public String getTemplateId() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.entry_history.template_uuid</code>.
	 */
	public void setTemplateUuid(UUID value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.template_uuid</code>.
	 */
	public UUID getTemplateUuid() {
		return (UUID) getValue(5);
	}

	/**
	 * Setter for <code>ehr.entry_history.archetype_id</code>.
	 */
	public void setArchetypeId(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.archetype_id</code>.
	 */
	public String getArchetypeId() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>ehr.entry_history.category</code>.
	 */
	public void setCategory(UUID value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.category</code>.
	 */
	public UUID getCategory() {
		return (UUID) getValue(7);
	}

	/**
	 * Setter for <code>ehr.entry_history.entry</code>.
	 */
	public void setEntry(Object value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.entry</code>.
	 */
	public Object getEntry() {
		return (Object) getValue(8);
	}

	/**
	 * Setter for <code>ehr.entry_history.sys_transaction</code>.
	 */
	public void setSysTransaction(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.sys_transaction</code>.
	 */
	public Timestamp getSysTransaction() {
		return (Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>ehr.entry_history.sys_period</code>.
	 */
	public void setSysPeriod(Object value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehr.entry_history.sys_period</code>.
	 */
	public Object getSysPeriod() {
		return (Object) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<UUID, UUID, Integer, EntryType, String, UUID, String, UUID, Object, Timestamp, Object> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<UUID, UUID, Integer, EntryType, String, UUID, String, UUID, Object, Timestamp, Object> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return EntryHistory.ENTRY_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return EntryHistory.ENTRY_HISTORY.COMPOSITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return EntryHistory.ENTRY_HISTORY.SEQUENCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<EntryType> field4() {
		return EntryHistory.ENTRY_HISTORY.ITEM_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return EntryHistory.ENTRY_HISTORY.TEMPLATE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field6() {
		return EntryHistory.ENTRY_HISTORY.TEMPLATE_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return EntryHistory.ENTRY_HISTORY.ARCHETYPE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field8() {
		return EntryHistory.ENTRY_HISTORY.CATEGORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field9() {
		return EntryHistory.ENTRY_HISTORY.ENTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return EntryHistory.ENTRY_HISTORY.SYS_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field11() {
		return EntryHistory.ENTRY_HISTORY.SYS_PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getCompositionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getSequence();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryType value4() {
		return getItemType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getTemplateId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value6() {
		return getTemplateUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getArchetypeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value8() {
		return getCategory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value9() {
		return getEntry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getSysTransaction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value11() {
		return getSysPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value1(UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value2(UUID value) {
		setCompositionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value3(Integer value) {
		setSequence(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value4(EntryType value) {
		setItemType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value5(String value) {
		setTemplateId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value6(UUID value) {
		setTemplateUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value7(String value) {
		setArchetypeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value8(UUID value) {
		setCategory(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value9(Object value) {
		setEntry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value10(Timestamp value) {
		setSysTransaction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord value11(Object value) {
		setSysPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntryHistoryRecord values(UUID value1, UUID value2, Integer value3, EntryType value4, String value5, UUID value6, String value7, UUID value8, Object value9, Timestamp value10, Object value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EntryHistoryRecord
	 */
	public EntryHistoryRecord() {
		super(EntryHistory.ENTRY_HISTORY);
	}

	/**
	 * Create a detached, initialised EntryHistoryRecord
	 */
	public EntryHistoryRecord(UUID id, UUID compositionId, Integer sequence, EntryType itemType, String templateId, UUID templateUuid, String archetypeId, UUID category, Object entry, Timestamp sysTransaction, Object sysPeriod) {
		super(EntryHistory.ENTRY_HISTORY);

		setValue(0, id);
		setValue(1, compositionId);
		setValue(2, sequence);
		setValue(3, itemType);
		setValue(4, templateId);
		setValue(5, templateUuid);
		setValue(6, archetypeId);
		setValue(7, category);
		setValue(8, entry);
		setValue(9, sysTransaction);
		setValue(10, sysPeriod);
	}
}
