/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.Keys;
import com.ethercis.jooq.pg.tables.records.StatusRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * specifies an ehr modality and ownership (patient)
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Status extends TableImpl<StatusRecord> {

	private static final long serialVersionUID = -169494038;

	/**
	 * The reference instance of <code>ehr.status</code>
	 */
	public static final Status STATUS = new Status();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StatusRecord> getRecordType() {
		return StatusRecord.class;
	}

	/**
	 * The column <code>ehr.status.id</code>.
	 */
	public final TableField<StatusRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehr.status.ehr_id</code>.
	 */
	public final TableField<StatusRecord, UUID> EHR_ID = createField("ehr_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.status.is_queryable</code>.
	 */
	public final TableField<StatusRecord, Boolean> IS_QUERYABLE = createField("is_queryable", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>ehr.status.is_modifiable</code>.
	 */
	public final TableField<StatusRecord, Boolean> IS_MODIFIABLE = createField("is_modifiable", org.jooq.impl.SQLDataType.BOOLEAN.defaulted(true), this, "");

	/**
	 * The column <code>ehr.status.party</code>.
	 */
	public final TableField<StatusRecord, UUID> PARTY = createField("party", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.status.other_details</code>.
	 */
	public final TableField<StatusRecord, Object> OTHER_DETAILS = createField("other_details", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>ehr.status.sys_transaction</code>.
	 */
	public final TableField<StatusRecord, Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.status.sys_period</code>.
	 */
	public final TableField<StatusRecord, Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.status</code> table reference
	 */
	public Status() {
		this("status", null);
	}

	/**
	 * Create an aliased <code>ehr.status</code> table reference
	 */
	public Status(String alias) {
		this(alias, STATUS);
	}

	private Status(String alias, Table<StatusRecord> aliased) {
		this(alias, aliased, null);
	}

	private Status(String alias, Table<StatusRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "specifies an ehr modality and ownership (patient)");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<StatusRecord> getPrimaryKey() {
		return Keys.STATUS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<StatusRecord>> getKeys() {
		return Arrays.<UniqueKey<StatusRecord>>asList(Keys.STATUS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<StatusRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<StatusRecord, ?>>asList(Keys.STATUS__STATUS_EHR_ID_FKEY, Keys.STATUS__STATUS_PARTY_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Status as(String alias) {
		return new Status(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Status rename(String name) {
		return new Status(name, null);
	}
}
