/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * defines the modality for accessing an com.ethercis.ehr (security strategy 
 * implementation)
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Access extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.AccessRecord> {

	private static final long serialVersionUID = -1422493719;

	/**
	 * The reference instance of <code>ehr.access</code>
	 */
	public static final com.ethercis.dao.jooq.tables.Access ACCESS = new com.ethercis.dao.jooq.tables.Access();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.AccessRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.AccessRecord.class;
	}

	/**
	 * The column <code>ehr.access.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.AccessRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehr.access.settings</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.AccessRecord, java.lang.String> SETTINGS = createField("settings", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>ehr.access.scheme</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.AccessRecord, java.lang.String> SCHEME = createField("scheme", org.jooq.impl.SQLDataType.CHAR.length(50), this, "");

	/**
	 * Create a <code>ehr.access</code> table reference
	 */
	public Access() {
		this("access", null);
	}

	/**
	 * Create an aliased <code>ehr.access</code> table reference
	 */
	public Access(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.Access.ACCESS);
	}

	private Access(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.AccessRecord> aliased) {
		this(alias, aliased, null);
	}

	private Access(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.AccessRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "defines the modality for accessing an com.ethercis.ehr (security strategy implementation)");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AccessRecord> getPrimaryKey() {
		return com.ethercis.dao.jooq.Keys.ACCESS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AccessRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AccessRecord>>asList(com.ethercis.dao.jooq.Keys.ACCESS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.Access as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.Access(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.Access rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.Access(name, null);
	}
}
