/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventContextHistory extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord> {

	private static final long serialVersionUID = 1768598254;

	/**
	 * The reference instance of <code>ehr.event_context_history</code>
	 */
	public static final com.ethercis.dao.jooq.tables.EventContextHistory EVENT_CONTEXT_HISTORY = new com.ethercis.dao.jooq.tables.EventContextHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord.class;
	}

	/**
	 * The column <code>ehr.event_context_history.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.event_context_history.composition_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.util.UUID> COMPOSITION_ID = createField("composition_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.event_context_history.start_time</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.sql.Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.event_context_history.start_time_tzid</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.lang.String> START_TIME_TZID = createField("start_time_tzid", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ehr.event_context_history.end_time</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.sql.Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehr.event_context_history.end_time_tzid</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.lang.String> END_TIME_TZID = createField("end_time_tzid", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ehr.event_context_history.facility</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.util.UUID> FACILITY = createField("facility", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.event_context_history.location</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.lang.String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.event_context_history.other_context</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.lang.Object> OTHER_CONTEXT = createField("other_context", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>ehr.event_context_history.setting</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.util.UUID> SETTING = createField("setting", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.event_context_history.sys_transaction</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.sql.Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.event_context_history.sys_period</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord, java.lang.Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.event_context_history</code> table reference
	 */
	public EventContextHistory() {
		this("event_context_history", null);
	}

	/**
	 * Create an aliased <code>ehr.event_context_history</code> table reference
	 */
	public EventContextHistory(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY);
	}

	private EventContextHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private EventContextHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.EventContextHistory as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.EventContextHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.EventContextHistory rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.EventContextHistory(name, null);
	}
}
