/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipationHistory extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord> {

	private static final long serialVersionUID = 1439217643;

	/**
	 * The reference instance of <code>ehr.participation_history</code>
	 */
	public static final com.ethercis.dao.jooq.tables.ParticipationHistory PARTICIPATION_HISTORY = new com.ethercis.dao.jooq.tables.ParticipationHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord.class;
	}

	/**
	 * The column <code>ehr.participation_history.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.participation_history.event_context</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.util.UUID> EVENT_CONTEXT = createField("event_context", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.participation_history.performer</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.util.UUID> PERFORMER = createField("performer", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.participation_history.function</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.lang.String> FUNCTION = createField("function", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.participation_history.mode</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.lang.String> MODE = createField("mode", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.participation_history.start_time</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.sql.Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehr.participation_history.start_time_tzid</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.lang.String> START_TIME_TZID = createField("start_time_tzid", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ehr.participation_history.sys_transaction</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.sql.Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.participation_history.sys_period</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord, java.lang.Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.participation_history</code> table reference
	 */
	public ParticipationHistory() {
		this("participation_history", null);
	}

	/**
	 * Create an aliased <code>ehr.participation_history</code> table reference
	 */
	public ParticipationHistory(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY);
	}

	private ParticipationHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private ParticipationHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.ParticipationHistory as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.ParticipationHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.ParticipationHistory rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.ParticipationHistory(name, null);
	}
}
