/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusHistory extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord> {

	private static final long serialVersionUID = 716799127;

	/**
	 * The reference instance of <code>ehr.status_history</code>
	 */
	public static final com.ethercis.dao.jooq.tables.StatusHistory STATUS_HISTORY = new com.ethercis.dao.jooq.tables.StatusHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.StatusHistoryRecord.class;
	}

	/**
	 * The column <code>ehr.status_history.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.status_history.ehr_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord, java.util.UUID> EHR_ID = createField("ehr_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.status_history.is_queryable</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord, java.lang.Boolean> IS_QUERYABLE = createField("is_queryable", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>ehr.status_history.is_modifiable</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord, java.lang.Boolean> IS_MODIFIABLE = createField("is_modifiable", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>ehr.status_history.party</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord, java.util.UUID> PARTY = createField("party", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.status_history.other_details</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord, java.lang.Object> OTHER_DETAILS = createField("other_details", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>ehr.status_history.sys_transaction</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord, java.sql.Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.status_history.sys_period</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord, java.lang.Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.status_history</code> table reference
	 */
	public StatusHistory() {
		this("status_history", null);
	}

	/**
	 * Create an aliased <code>ehr.status_history</code> table reference
	 */
	public StatusHistory(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.StatusHistory.STATUS_HISTORY);
	}

	private StatusHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private StatusHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.StatusHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.StatusHistory as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.StatusHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.StatusHistory rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.StatusHistory(name, null);
	}
}
