/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg;


import com.ethercis.jooq.pg.routines._AqlLabelize;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in ehr
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>ehr._aql_labelize</code>
	 */
	public static String _AqlLabelize(Configuration configuration, String rawArchetype) {
		_AqlLabelize f = new _AqlLabelize();
		f.setRawArchetype(rawArchetype);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>ehr._aql_labelize</code> as a field.
	 */
	public static Field<String> _AqlLabelize(String rawArchetype) {
		_AqlLabelize f = new _AqlLabelize();
		f.setRawArchetype(rawArchetype);

		return f.asField();
	}

	/**
	 * Get <code>ehr._aql_labelize</code> as a field.
	 */
	public static Field<String> _AqlLabelize(Field<String> rawArchetype) {
		_AqlLabelize f = new _AqlLabelize();
		f.setRawArchetype(rawArchetype);

		return f.asField();
	}
}
