/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.routines;


import com.ethercis.jooq.pg.Ehr;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _AqlLabelize extends AbstractRoutine<String> {

	private static final long serialVersionUID = -336816154;

	/**
	 * The parameter <code>ehr._aql_labelize.RETURN_VALUE</code>.
	 */
	public static final Parameter<String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB, false);

	/**
	 * The parameter <code>ehr._aql_labelize.raw_archetype</code>.
	 */
	public static final Parameter<String> RAW_ARCHETYPE = createParameter("raw_archetype", org.jooq.impl.SQLDataType.CLOB, false);

	/**
	 * Create a new routine call instance
	 */
	public _AqlLabelize() {
		super("_aql_labelize", Ehr.EHR, org.jooq.impl.SQLDataType.CLOB);

		setReturnParameter(RETURN_VALUE);
		addInParameter(RAW_ARCHETYPE);
	}

	/**
	 * Set the <code>raw_archetype</code> parameter IN value to the routine
	 */
	public void setRawArchetype(String value) {
		setValue(RAW_ARCHETYPE, value);
	}

	/**
	 * Set the <code>raw_archetype</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setRawArchetype(Field<String> field) {
		setField(RAW_ARCHETYPE, field);
	}
}
