/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * openEHR common concepts (e.g. terminology) used in the system
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Concept extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.ConceptRecord> {

	private static final long serialVersionUID = 1215007470;

	/**
	 * The reference instance of <code>ehr.concept</code>
	 */
	public static final com.ethercis.dao.jooq.tables.Concept CONCEPT = new com.ethercis.dao.jooq.tables.Concept();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.ConceptRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.ConceptRecord.class;
	}

	/**
	 * The column <code>ehr.concept.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ConceptRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehr.concept.conceptid</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ConceptRecord, java.lang.Integer> CONCEPTID = createField("conceptid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ehr.concept.language</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ConceptRecord, java.lang.String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * The column <code>ehr.concept.description</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ConceptRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * Create a <code>ehr.concept</code> table reference
	 */
	public Concept() {
		this("concept", null);
	}

	/**
	 * Create an aliased <code>ehr.concept</code> table reference
	 */
	public Concept(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.Concept.CONCEPT);
	}

	private Concept(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.ConceptRecord> aliased) {
		this(alias, aliased, null);
	}

	private Concept(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.ConceptRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "openEHR common concepts (e.g. terminology) used in the system");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ConceptRecord> getPrimaryKey() {
		return com.ethercis.dao.jooq.Keys.CONCEPT_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ConceptRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ConceptRecord>>asList(com.ethercis.dao.jooq.Keys.CONCEPT_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ConceptRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ConceptRecord, ?>>asList(com.ethercis.dao.jooq.Keys.CONCEPT__CONCEPT_LANGUAGE_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.Concept as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.Concept(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.Concept rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.Concept(name, null);
	}
}
