/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * Contribution table, compositions reference this table
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contribution extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.ContributionRecord> {

	private static final long serialVersionUID = 839381386;

	/**
	 * The reference instance of <code>ehr.contribution</code>
	 */
	public static final com.ethercis.dao.jooq.tables.Contribution CONTRIBUTION = new com.ethercis.dao.jooq.tables.Contribution();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.ContributionRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.ContributionRecord.class;
	}

	/**
	 * The column <code>ehr.contribution.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehr.contribution.ehr_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.util.UUID> EHR_ID = createField("ehr_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution.contribution_type</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, com.ethercis.dao.jooq.enums.ContributionDataType> CONTRIBUTION_TYPE = createField("contribution_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.dao.jooq.enums.ContributionDataType.class), this, "");

	/**
	 * The column <code>ehr.contribution.state</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, com.ethercis.dao.jooq.enums.ContributionState> STATE = createField("state", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.dao.jooq.enums.ContributionState.class), this, "");

	/**
	 * The column <code>ehr.contribution.signature</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.lang.String> SIGNATURE = createField("signature", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.contribution.system_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.util.UUID> SYSTEM_ID = createField("system_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution.committer</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.util.UUID> COMMITTER = createField("committer", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution.time_committed</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.sql.Timestamp> TIME_COMMITTED = createField("time_committed", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>ehr.contribution.change_type</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.util.UUID> CHANGE_TYPE = createField("change_type", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution.description</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>ehr.contribution.sys_transaction</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.sql.Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.contribution.sys_period</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionRecord, java.lang.Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.contribution</code> table reference
	 */
	public Contribution() {
		this("contribution", null);
	}

	/**
	 * Create an aliased <code>ehr.contribution</code> table reference
	 */
	public Contribution(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION);
	}

	private Contribution(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.ContributionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Contribution(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.ContributionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "Contribution table, compositions reference this table");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ContributionRecord> getPrimaryKey() {
		return com.ethercis.dao.jooq.Keys.CONTRIBUTION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ContributionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ContributionRecord>>asList(com.ethercis.dao.jooq.Keys.CONTRIBUTION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ContributionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ContributionRecord, ?>>asList(com.ethercis.dao.jooq.Keys.CONTRIBUTION__CONTRIBUTION_EHR_ID_FKEY, com.ethercis.dao.jooq.Keys.CONTRIBUTION__CONTRIBUTION_SYSTEM_ID_FKEY, com.ethercis.dao.jooq.Keys.CONTRIBUTION__CONTRIBUTION_COMMITTER_FKEY, com.ethercis.dao.jooq.Keys.CONTRIBUTION__CONTRIBUTION_CHANGE_TYPE_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.Contribution as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.Contribution(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.Contribution rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.Contribution(name, null);
	}
}
