/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributionHistory extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord> {

	private static final long serialVersionUID = 1889269059;

	/**
	 * The reference instance of <code>ehr.contribution_history</code>
	 */
	public static final com.ethercis.dao.jooq.tables.ContributionHistory CONTRIBUTION_HISTORY = new com.ethercis.dao.jooq.tables.ContributionHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord.class;
	}

	/**
	 * The column <code>ehr.contribution_history.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.contribution_history.ehr_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.util.UUID> EHR_ID = createField("ehr_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution_history.contribution_type</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, com.ethercis.dao.jooq.enums.ContributionDataType> CONTRIBUTION_TYPE = createField("contribution_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.dao.jooq.enums.ContributionDataType.class), this, "");

	/**
	 * The column <code>ehr.contribution_history.state</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, com.ethercis.dao.jooq.enums.ContributionState> STATE = createField("state", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.dao.jooq.enums.ContributionState.class), this, "");

	/**
	 * The column <code>ehr.contribution_history.signature</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.lang.String> SIGNATURE = createField("signature", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.contribution_history.system_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.util.UUID> SYSTEM_ID = createField("system_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution_history.committer</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.util.UUID> COMMITTER = createField("committer", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution_history.time_committed</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.sql.Timestamp> TIME_COMMITTED = createField("time_committed", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehr.contribution_history.change_type</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.util.UUID> CHANGE_TYPE = createField("change_type", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution_history.description</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>ehr.contribution_history.sys_transaction</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.sql.Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.contribution_history.sys_period</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord, java.lang.Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.contribution_history</code> table reference
	 */
	public ContributionHistory() {
		this("contribution_history", null);
	}

	/**
	 * Create an aliased <code>ehr.contribution_history</code> table reference
	 */
	public ContributionHistory(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY);
	}

	private ContributionHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContributionHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.ContributionHistory as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.ContributionHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.ContributionHistory rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.ContributionHistory(name, null);
	}
}
