/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntryHistory extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord> {

	private static final long serialVersionUID = -1417262604;

	/**
	 * The reference instance of <code>ehr.entry_history</code>
	 */
	public static final com.ethercis.dao.jooq.tables.EntryHistory ENTRY_HISTORY = new com.ethercis.dao.jooq.tables.EntryHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.EntryHistoryRecord.class;
	}

	/**
	 * The column <code>ehr.entry_history.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.entry_history.composition_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.util.UUID> COMPOSITION_ID = createField("composition_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.entry_history.sequence</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.lang.Integer> SEQUENCE = createField("sequence", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ehr.entry_history.item_type</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, com.ethercis.dao.jooq.enums.EntryType> ITEM_TYPE = createField("item_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.dao.jooq.enums.EntryType.class), this, "");

	/**
	 * The column <code>ehr.entry_history.template_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.lang.String> TEMPLATE_ID = createField("template_id", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>ehr.entry_history.template_uuid</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.util.UUID> TEMPLATE_UUID = createField("template_uuid", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.entry_history.archetype_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.lang.String> ARCHETYPE_ID = createField("archetype_id", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>ehr.entry_history.category</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.util.UUID> CATEGORY = createField("category", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.entry_history.entry</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.lang.Object> ENTRY = createField("entry", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>ehr.entry_history.sys_transaction</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.sql.Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.entry_history.sys_period</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord, java.lang.Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.entry_history</code> table reference
	 */
	public EntryHistory() {
		this("entry_history", null);
	}

	/**
	 * Create an aliased <code>ehr.entry_history</code> table reference
	 */
	public EntryHistory(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.EntryHistory.ENTRY_HISTORY);
	}

	private EntryHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private EntryHistory(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.EntryHistoryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.EntryHistory as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.EntryHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.EntryHistory rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.EntryHistory(name, null);
	}
}
