/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * this table hold the actual archetyped data values (from a template)
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entry extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.EntryRecord> {

	private static final long serialVersionUID = 271443925;

	/**
	 * The reference instance of <code>ehr.entry</code>
	 */
	public static final com.ethercis.dao.jooq.tables.Entry ENTRY = new com.ethercis.dao.jooq.tables.Entry();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.EntryRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.EntryRecord.class;
	}

	/**
	 * The column <code>ehr.entry.id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.util.UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehr.entry.composition_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.util.UUID> COMPOSITION_ID = createField("composition_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.entry.sequence</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.lang.Integer> SEQUENCE = createField("sequence", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ehr.entry.item_type</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, com.ethercis.dao.jooq.enums.EntryType> ITEM_TYPE = createField("item_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.dao.jooq.enums.EntryType.class), this, "");

	/**
	 * The column <code>ehr.entry.template_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.lang.String> TEMPLATE_ID = createField("template_id", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>ehr.entry.template_uuid</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.util.UUID> TEMPLATE_UUID = createField("template_uuid", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.entry.archetype_id</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.lang.String> ARCHETYPE_ID = createField("archetype_id", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>ehr.entry.category</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.util.UUID> CATEGORY = createField("category", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.entry.entry</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.lang.Object> ENTRY_ = createField("entry", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>ehr.entry.sys_transaction</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.sql.Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.entry.sys_period</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.EntryRecord, java.lang.Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.entry</code> table reference
	 */
	public Entry() {
		this("entry", null);
	}

	/**
	 * Create an aliased <code>ehr.entry</code> table reference
	 */
	public Entry(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.Entry.ENTRY);
	}

	private Entry(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.EntryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Entry(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.EntryRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "this table hold the actual archetyped data values (from a template)");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EntryRecord> getPrimaryKey() {
		return com.ethercis.dao.jooq.Keys.ENTRY_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EntryRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EntryRecord>>asList(com.ethercis.dao.jooq.Keys.ENTRY_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EntryRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EntryRecord, ?>>asList(com.ethercis.dao.jooq.Keys.ENTRY__ENTRY_COMPOSITION_ID_FKEY, com.ethercis.dao.jooq.Keys.ENTRY__ENTRY_CATEGORY_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.Entry as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.Entry(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.Entry rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.Entry(name, null);
	}
}
