/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * ISO 639-1 language codeset
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.LanguageRecord> {

	private static final long serialVersionUID = 1234463470;

	/**
	 * The reference instance of <code>ehr.language</code>
	 */
	public static final com.ethercis.dao.jooq.tables.Language LANGUAGE = new com.ethercis.dao.jooq.tables.Language();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.LanguageRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.LanguageRecord.class;
	}

	/**
	 * The column <code>ehr.language.code</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.LanguageRecord, java.lang.String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(5).nullable(false), this, "");

	/**
	 * The column <code>ehr.language.description</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.LanguageRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>ehr.language</code> table reference
	 */
	public Language() {
		this("language", null);
	}

	/**
	 * Create an aliased <code>ehr.language</code> table reference
	 */
	public Language(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.Language.LANGUAGE);
	}

	private Language(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.LanguageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Language(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.LanguageRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "ISO 639-1 language codeset");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.LanguageRecord> getPrimaryKey() {
		return com.ethercis.dao.jooq.Keys.LANGUAGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.LanguageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.LanguageRecord>>asList(com.ethercis.dao.jooq.Keys.LANGUAGE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.Language as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.Language(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.Language rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.Language(name, null);
	}
}
