/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables;

/**
 * openEHR identified terminology provider
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TerminologyProvider extends org.jooq.impl.TableImpl<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord> {

	private static final long serialVersionUID = -1702867990;

	/**
	 * The reference instance of <code>ehr.terminology_provider</code>
	 */
	public static final com.ethercis.dao.jooq.tables.TerminologyProvider TERMINOLOGY_PROVIDER = new com.ethercis.dao.jooq.tables.TerminologyProvider();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord> getRecordType() {
		return com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord.class;
	}

	/**
	 * The column <code>ehr.terminology_provider.code</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord, java.lang.String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>ehr.terminology_provider.source</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord, java.lang.String> SOURCE = createField("source", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>ehr.terminology_provider.authority</code>.
	 */
	public final org.jooq.TableField<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord, java.lang.String> AUTHORITY = createField("authority", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>ehr.terminology_provider</code> table reference
	 */
	public TerminologyProvider() {
		this("terminology_provider", null);
	}

	/**
	 * Create an aliased <code>ehr.terminology_provider</code> table reference
	 */
	public TerminologyProvider(java.lang.String alias) {
		this(alias, com.ethercis.dao.jooq.tables.TerminologyProvider.TERMINOLOGY_PROVIDER);
	}

	private TerminologyProvider(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord> aliased) {
		this(alias, aliased, null);
	}

	private TerminologyProvider(java.lang.String alias, org.jooq.Table<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ethercis.dao.jooq.Ehr.EHR, aliased, parameters, "openEHR identified terminology provider");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord> getPrimaryKey() {
		return com.ethercis.dao.jooq.Keys.TERMINOLOGY_PROVIDER_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord>>asList(com.ethercis.dao.jooq.Keys.TERMINOLOGY_PROVIDER_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.tables.TerminologyProvider as(java.lang.String alias) {
		return new com.ethercis.dao.jooq.tables.TerminologyProvider(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ethercis.dao.jooq.tables.TerminologyProvider rename(java.lang.String name) {
		return new com.ethercis.dao.jooq.tables.TerminologyProvider(name, null);
	}
}
