/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttestedViewRecord extends org.jooq.impl.UpdatableRecordImpl<com.ethercis.dao.jooq.tables.records.AttestedViewRecord> implements org.jooq.Record10<java.util.UUID, java.util.UUID, java.lang.String, java.lang.String, java.lang.String, byte[], byte[], java.lang.String, java.util.UUID, java.lang.String> {

	private static final long serialVersionUID = 268800830;

	/**
	 * Setter for <code>ehr.attested_view.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.attested_view.attestation_id</code>.
	 */
	public void setAttestationId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.attestation_id</code>.
	 */
	public java.util.UUID getAttestationId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.attested_view.alternate_text</code>.
	 */
	public void setAlternateText(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.alternate_text</code>.
	 */
	public java.lang.String getAlternateText() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehr.attested_view.compression_algorithm</code>.
	 */
	public void setCompressionAlgorithm(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.compression_algorithm</code>.
	 */
	public java.lang.String getCompressionAlgorithm() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehr.attested_view.media_type</code>.
	 */
	public void setMediaType(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.media_type</code>.
	 */
	public java.lang.String getMediaType() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.attested_view.data</code>.
	 */
	public void setData(byte[] value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.data</code>.
	 */
	public byte[] getData() {
		return (byte[]) getValue(5);
	}

	/**
	 * Setter for <code>ehr.attested_view.integrity_check</code>.
	 */
	public void setIntegrityCheck(byte[] value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.integrity_check</code>.
	 */
	public byte[] getIntegrityCheck() {
		return (byte[]) getValue(6);
	}

	/**
	 * Setter for <code>ehr.attested_view.integrity_check_algorithm</code>.
	 */
	public void setIntegrityCheckAlgorithm(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.integrity_check_algorithm</code>.
	 */
	public java.lang.String getIntegrityCheckAlgorithm() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>ehr.attested_view.thumbnail</code>.
	 */
	public void setThumbnail(java.util.UUID value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.thumbnail</code>.
	 */
	public java.util.UUID getThumbnail() {
		return (java.util.UUID) getValue(8);
	}

	/**
	 * Setter for <code>ehr.attested_view.uri</code>.
	 */
	public void setUri(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehr.attested_view.uri</code>.
	 */
	public java.lang.String getUri() {
		return (java.lang.String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.util.UUID, java.util.UUID, java.lang.String, java.lang.String, java.lang.String, byte[], byte[], java.lang.String, java.util.UUID, java.lang.String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.util.UUID, java.util.UUID, java.lang.String, java.lang.String, java.lang.String, byte[], byte[], java.lang.String, java.util.UUID, java.lang.String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.ATTESTATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.ALTERNATE_TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.COMPRESSION_ALGORITHM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.MEDIA_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field6() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field7() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.INTEGRITY_CHECK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.INTEGRITY_CHECK_ALGORITHM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field9() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.THUMBNAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.URI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getAttestationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAlternateText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCompressionAlgorithm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getMediaType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value6() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value7() {
		return getIntegrityCheck();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getIntegrityCheckAlgorithm();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value9() {
		return getThumbnail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getUri();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value2(java.util.UUID value) {
		setAttestationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value3(java.lang.String value) {
		setAlternateText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value4(java.lang.String value) {
		setCompressionAlgorithm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value5(java.lang.String value) {
		setMediaType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value6(byte[] value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value7(byte[] value) {
		setIntegrityCheck(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value8(java.lang.String value) {
		setIntegrityCheckAlgorithm(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value9(java.util.UUID value) {
		setThumbnail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord value10(java.lang.String value) {
		setUri(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AttestedViewRecord values(java.util.UUID value1, java.util.UUID value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, byte[] value6, byte[] value7, java.lang.String value8, java.util.UUID value9, java.lang.String value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AttestedViewRecord
	 */
	public AttestedViewRecord() {
		super(com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW);
	}

	/**
	 * Create a detached, initialised AttestedViewRecord
	 */
	public AttestedViewRecord(java.util.UUID id, java.util.UUID attestationId, java.lang.String alternateText, java.lang.String compressionAlgorithm, java.lang.String mediaType, byte[] data, byte[] integrityCheck, java.lang.String integrityCheckAlgorithm, java.util.UUID thumbnail, java.lang.String uri) {
		super(com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW);

		setValue(0, id);
		setValue(1, attestationId);
		setValue(2, alternateText);
		setValue(3, compressionAlgorithm);
		setValue(4, mediaType);
		setValue(5, data);
		setValue(6, integrityCheck);
		setValue(7, integrityCheckAlgorithm);
		setValue(8, thumbnail);
		setValue(9, uri);
	}
}
