/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * Contribution table, compositions reference this table
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributionRecord extends org.jooq.impl.UpdatableRecordImpl<com.ethercis.dao.jooq.tables.records.ContributionRecord> implements org.jooq.Record13<java.util.UUID, java.util.UUID, com.ethercis.dao.jooq.enums.ContributionDataType, com.ethercis.dao.jooq.enums.ContributionState, java.lang.String, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.lang.String, com.ethercis.dao.jooq.enums.ContributionChangeType, java.lang.String, java.sql.Timestamp, java.lang.Object> {

	private static final long serialVersionUID = 130972811;

	/**
	 * Setter for <code>ehr.contribution.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.contribution.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.contribution.ehr_id</code>.
	 */
	public void setEhrId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.contribution.ehr_id</code>.
	 */
	public java.util.UUID getEhrId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.contribution.contribution_type</code>.
	 */
	public void setContributionType(com.ethercis.dao.jooq.enums.ContributionDataType value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.contribution.contribution_type</code>.
	 */
	public com.ethercis.dao.jooq.enums.ContributionDataType getContributionType() {
		return (com.ethercis.dao.jooq.enums.ContributionDataType) getValue(2);
	}

	/**
	 * Setter for <code>ehr.contribution.state</code>.
	 */
	public void setState(com.ethercis.dao.jooq.enums.ContributionState value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.contribution.state</code>.
	 */
	public com.ethercis.dao.jooq.enums.ContributionState getState() {
		return (com.ethercis.dao.jooq.enums.ContributionState) getValue(3);
	}

	/**
	 * Setter for <code>ehr.contribution.signature</code>.
	 */
	public void setSignature(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.contribution.signature</code>.
	 */
	public java.lang.String getSignature() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.contribution.system_id</code>.
	 */
	public void setSystemId(java.util.UUID value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.contribution.system_id</code>.
	 */
	public java.util.UUID getSystemId() {
		return (java.util.UUID) getValue(5);
	}

	/**
	 * Setter for <code>ehr.contribution.committer</code>.
	 */
	public void setCommitter(java.util.UUID value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.contribution.committer</code>.
	 */
	public java.util.UUID getCommitter() {
		return (java.util.UUID) getValue(6);
	}

	/**
	 * Setter for <code>ehr.contribution.time_committed</code>.
	 */
	public void setTimeCommitted(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.contribution.time_committed</code>.
	 */
	public java.sql.Timestamp getTimeCommitted() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>ehr.contribution.time_committed_tzid</code>.
	 */
	public void setTimeCommittedTzid(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.contribution.time_committed_tzid</code>.
	 */
	public java.lang.String getTimeCommittedTzid() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>ehr.contribution.change_type</code>.
	 */
	public void setChangeType(com.ethercis.dao.jooq.enums.ContributionChangeType value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehr.contribution.change_type</code>.
	 */
	public com.ethercis.dao.jooq.enums.ContributionChangeType getChangeType() {
		return (com.ethercis.dao.jooq.enums.ContributionChangeType) getValue(9);
	}

	/**
	 * Setter for <code>ehr.contribution.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehr.contribution.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>ehr.contribution.sys_transaction</code>.
	 */
	public void setSysTransaction(java.sql.Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehr.contribution.sys_transaction</code>.
	 */
	public java.sql.Timestamp getSysTransaction() {
		return (java.sql.Timestamp) getValue(11);
	}

	/**
	 * Setter for <code>ehr.contribution.sys_period</code>.
	 */
	public void setSysPeriod(java.lang.Object value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>ehr.contribution.sys_period</code>.
	 */
	public java.lang.Object getSysPeriod() {
		return (java.lang.Object) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.util.UUID, java.util.UUID, com.ethercis.dao.jooq.enums.ContributionDataType, com.ethercis.dao.jooq.enums.ContributionState, java.lang.String, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.lang.String, com.ethercis.dao.jooq.enums.ContributionChangeType, java.lang.String, java.sql.Timestamp, java.lang.Object> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.util.UUID, java.util.UUID, com.ethercis.dao.jooq.enums.ContributionDataType, com.ethercis.dao.jooq.enums.ContributionState, java.lang.String, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.lang.String, com.ethercis.dao.jooq.enums.ContributionChangeType, java.lang.String, java.sql.Timestamp, java.lang.Object> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.EHR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.ethercis.dao.jooq.enums.ContributionDataType> field3() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.CONTRIBUTION_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.ethercis.dao.jooq.enums.ContributionState> field4() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.SIGNATURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field6() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.SYSTEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field7() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.COMMITTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.TIME_COMMITTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.TIME_COMMITTED_TZID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.ethercis.dao.jooq.enums.ContributionChangeType> field10() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.CHANGE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field12() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.SYS_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field13() {
		return com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.SYS_PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getEhrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.enums.ContributionDataType value3() {
		return getContributionType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.enums.ContributionState value4() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSignature();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value6() {
		return getSystemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value7() {
		return getCommitter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getTimeCommitted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getTimeCommittedTzid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.enums.ContributionChangeType value10() {
		return getChangeType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value12() {
		return getSysTransaction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value13() {
		return getSysPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value2(java.util.UUID value) {
		setEhrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value3(com.ethercis.dao.jooq.enums.ContributionDataType value) {
		setContributionType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value4(com.ethercis.dao.jooq.enums.ContributionState value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value5(java.lang.String value) {
		setSignature(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value6(java.util.UUID value) {
		setSystemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value7(java.util.UUID value) {
		setCommitter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value8(java.sql.Timestamp value) {
		setTimeCommitted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value9(java.lang.String value) {
		setTimeCommittedTzid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value10(com.ethercis.dao.jooq.enums.ContributionChangeType value) {
		setChangeType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value11(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value12(java.sql.Timestamp value) {
		setSysTransaction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord value13(java.lang.Object value) {
		setSysPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionRecord values(java.util.UUID value1, java.util.UUID value2, com.ethercis.dao.jooq.enums.ContributionDataType value3, com.ethercis.dao.jooq.enums.ContributionState value4, java.lang.String value5, java.util.UUID value6, java.util.UUID value7, java.sql.Timestamp value8, java.lang.String value9, com.ethercis.dao.jooq.enums.ContributionChangeType value10, java.lang.String value11, java.sql.Timestamp value12, java.lang.Object value13) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContributionRecord
	 */
	public ContributionRecord() {
		super(com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION);
	}

	/**
	 * Create a detached, initialised ContributionRecord
	 */
	public ContributionRecord(java.util.UUID id, java.util.UUID ehrId, com.ethercis.dao.jooq.enums.ContributionDataType contributionType, com.ethercis.dao.jooq.enums.ContributionState state, java.lang.String signature, java.util.UUID systemId, java.util.UUID committer, java.sql.Timestamp timeCommitted, java.lang.String timeCommittedTzid, com.ethercis.dao.jooq.enums.ContributionChangeType changeType, java.lang.String description, java.sql.Timestamp sysTransaction, java.lang.Object sysPeriod) {
		super(com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION);

		setValue(0, id);
		setValue(1, ehrId);
		setValue(2, contributionType);
		setValue(3, state);
		setValue(4, signature);
		setValue(5, systemId);
		setValue(6, committer);
		setValue(7, timeCommitted);
		setValue(8, timeCommittedTzid);
		setValue(9, changeType);
		setValue(10, description);
		setValue(11, sysTransaction);
		setValue(12, sysPeriod);
	}
}
