/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventContextHistoryRecord extends org.jooq.impl.TableRecordImpl<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord> implements org.jooq.Record12<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.util.UUID, java.lang.String, java.lang.Object, java.util.UUID, java.sql.Timestamp, java.lang.Object> {

	private static final long serialVersionUID = 1185064980;

	/**
	 * Setter for <code>ehr.event_context_history.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.event_context_history.composition_id</code>.
	 */
	public void setCompositionId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.composition_id</code>.
	 */
	public java.util.UUID getCompositionId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.event_context_history.start_time</code>.
	 */
	public void setStartTime(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.start_time</code>.
	 */
	public java.sql.Timestamp getStartTime() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>ehr.event_context_history.start_time_tzid</code>.
	 */
	public void setStartTimeTzid(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.start_time_tzid</code>.
	 */
	public java.lang.String getStartTimeTzid() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehr.event_context_history.end_time</code>.
	 */
	public void setEndTime(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.end_time</code>.
	 */
	public java.sql.Timestamp getEndTime() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>ehr.event_context_history.end_time_tzid</code>.
	 */
	public void setEndTimeTzid(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.end_time_tzid</code>.
	 */
	public java.lang.String getEndTimeTzid() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehr.event_context_history.facility</code>.
	 */
	public void setFacility(java.util.UUID value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.facility</code>.
	 */
	public java.util.UUID getFacility() {
		return (java.util.UUID) getValue(6);
	}

	/**
	 * Setter for <code>ehr.event_context_history.location</code>.
	 */
	public void setLocation(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.location</code>.
	 */
	public java.lang.String getLocation() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>ehr.event_context_history.other_context</code>.
	 */
	public void setOtherContext(java.lang.Object value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.other_context</code>.
	 */
	public java.lang.Object getOtherContext() {
		return (java.lang.Object) getValue(8);
	}

	/**
	 * Setter for <code>ehr.event_context_history.setting</code>.
	 */
	public void setSetting(java.util.UUID value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.setting</code>.
	 */
	public java.util.UUID getSetting() {
		return (java.util.UUID) getValue(9);
	}

	/**
	 * Setter for <code>ehr.event_context_history.sys_transaction</code>.
	 */
	public void setSysTransaction(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.sys_transaction</code>.
	 */
	public java.sql.Timestamp getSysTransaction() {
		return (java.sql.Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>ehr.event_context_history.sys_period</code>.
	 */
	public void setSysPeriod(java.lang.Object value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.sys_period</code>.
	 */
	public java.lang.Object getSysPeriod() {
		return (java.lang.Object) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.util.UUID, java.lang.String, java.lang.Object, java.util.UUID, java.sql.Timestamp, java.lang.Object> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.String, java.util.UUID, java.lang.String, java.lang.Object, java.util.UUID, java.sql.Timestamp, java.lang.Object> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.COMPOSITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.START_TIME_TZID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.END_TIME_TZID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field7() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.FACILITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field9() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.OTHER_CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field10() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.SETTING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.SYS_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field12() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.SYS_PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getCompositionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getStartTimeTzid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getEndTimeTzid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value7() {
		return getFacility();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value9() {
		return getOtherContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value10() {
		return getSetting();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getSysTransaction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value12() {
		return getSysPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value2(java.util.UUID value) {
		setCompositionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value3(java.sql.Timestamp value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value4(java.lang.String value) {
		setStartTimeTzid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value5(java.sql.Timestamp value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value6(java.lang.String value) {
		setEndTimeTzid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value7(java.util.UUID value) {
		setFacility(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value8(java.lang.String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value9(java.lang.Object value) {
		setOtherContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value10(java.util.UUID value) {
		setSetting(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value11(java.sql.Timestamp value) {
		setSysTransaction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value12(java.lang.Object value) {
		setSysPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord values(java.util.UUID value1, java.util.UUID value2, java.sql.Timestamp value3, java.lang.String value4, java.sql.Timestamp value5, java.lang.String value6, java.util.UUID value7, java.lang.String value8, java.lang.Object value9, java.util.UUID value10, java.sql.Timestamp value11, java.lang.Object value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventContextHistoryRecord
	 */
	public EventContextHistoryRecord() {
		super(com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY);
	}

	/**
	 * Create a detached, initialised EventContextHistoryRecord
	 */
	public EventContextHistoryRecord(java.util.UUID id, java.util.UUID compositionId, java.sql.Timestamp startTime, java.lang.String startTimeTzid, java.sql.Timestamp endTime, java.lang.String endTimeTzid, java.util.UUID facility, java.lang.String location, java.lang.Object otherContext, java.util.UUID setting, java.sql.Timestamp sysTransaction, java.lang.Object sysPeriod) {
		super(com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY);

		setValue(0, id);
		setValue(1, compositionId);
		setValue(2, startTime);
		setValue(3, startTimeTzid);
		setValue(4, endTime);
		setValue(5, endTimeTzid);
		setValue(6, facility);
		setValue(7, location);
		setValue(8, otherContext);
		setValue(9, setting);
		setValue(10, sysTransaction);
		setValue(11, sysPeriod);
	}
}
