/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyIdentifiedRecord extends org.jooq.impl.UpdatableRecordImpl<com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> implements org.jooq.Record6<java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -272216109;

	/**
	 * Setter for <code>ehr.party_identified.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.party_identified.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.party_identified.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.party_identified.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ehr.party_identified.party_ref_value</code>.
	 */
	public void setPartyRefValue(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.party_identified.party_ref_value</code>.
	 */
	public java.lang.String getPartyRefValue() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehr.party_identified.party_ref_scheme</code>.
	 */
	public void setPartyRefScheme(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.party_identified.party_ref_scheme</code>.
	 */
	public java.lang.String getPartyRefScheme() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehr.party_identified.party_ref_namespace</code>.
	 */
	public void setPartyRefNamespace(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.party_identified.party_ref_namespace</code>.
	 */
	public java.lang.String getPartyRefNamespace() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.party_identified.party_ref_type</code>.
	 */
	public void setPartyRefType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.party_identified.party_ref_type</code>.
	 */
	public java.lang.String getPartyRefType() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.util.UUID, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED.PARTY_REF_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED.PARTY_REF_SCHEME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED.PARTY_REF_NAMESPACE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED.PARTY_REF_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPartyRefValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPartyRefScheme();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPartyRefNamespace();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getPartyRefType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartyIdentifiedRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartyIdentifiedRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartyIdentifiedRecord value3(java.lang.String value) {
		setPartyRefValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartyIdentifiedRecord value4(java.lang.String value) {
		setPartyRefScheme(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartyIdentifiedRecord value5(java.lang.String value) {
		setPartyRefNamespace(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartyIdentifiedRecord value6(java.lang.String value) {
		setPartyRefType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PartyIdentifiedRecord values(java.util.UUID value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PartyIdentifiedRecord
	 */
	public PartyIdentifiedRecord() {
		super(com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED);
	}

	/**
	 * Create a detached, initialised PartyIdentifiedRecord
	 */
	public PartyIdentifiedRecord(java.util.UUID id, java.lang.String name, java.lang.String partyRefValue, java.lang.String partyRefScheme, java.lang.String partyRefNamespace, java.lang.String partyRefType) {
		super(com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED);

		setValue(0, id);
		setValue(1, name);
		setValue(2, partyRefValue);
		setValue(3, partyRefScheme);
		setValue(4, partyRefNamespace);
		setValue(5, partyRefType);
	}
}
