/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipationHistoryRecord extends org.jooq.impl.TableRecordImpl<com.ethercis.dao.jooq.tables.records.ParticipationHistoryRecord> implements org.jooq.Record9<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.Object> {

	private static final long serialVersionUID = -454228963;

	/**
	 * Setter for <code>ehr.participation_history.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.participation_history.event_context</code>.
	 */
	public void setEventContext(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.event_context</code>.
	 */
	public java.util.UUID getEventContext() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.participation_history.performer</code>.
	 */
	public void setPerformer(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.performer</code>.
	 */
	public java.util.UUID getPerformer() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>ehr.participation_history.function</code>.
	 */
	public void setFunction(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.function</code>.
	 */
	public java.lang.String getFunction() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>ehr.participation_history.mode</code>.
	 */
	public void setMode(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.mode</code>.
	 */
	public java.lang.String getMode() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.participation_history.start_time</code>.
	 */
	public void setStartTime(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.start_time</code>.
	 */
	public java.sql.Timestamp getStartTime() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>ehr.participation_history.start_time_tzid</code>.
	 */
	public void setStartTimeTzid(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.start_time_tzid</code>.
	 */
	public java.lang.String getStartTimeTzid() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>ehr.participation_history.sys_transaction</code>.
	 */
	public void setSysTransaction(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.sys_transaction</code>.
	 */
	public java.sql.Timestamp getSysTransaction() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>ehr.participation_history.sys_period</code>.
	 */
	public void setSysPeriod(java.lang.Object value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.participation_history.sys_period</code>.
	 */
	public java.lang.Object getSysPeriod() {
		return (java.lang.Object) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.Object> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.sql.Timestamp, java.lang.Object> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.EVENT_CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.PERFORMER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.FUNCTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.MODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.START_TIME_TZID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.SYS_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field9() {
		return com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY.SYS_PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getEventContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getPerformer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getFunction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getMode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getStartTimeTzid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getSysTransaction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value9() {
		return getSysPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value2(java.util.UUID value) {
		setEventContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value3(java.util.UUID value) {
		setPerformer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value4(java.lang.String value) {
		setFunction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value5(java.lang.String value) {
		setMode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value6(java.sql.Timestamp value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value7(java.lang.String value) {
		setStartTimeTzid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value8(java.sql.Timestamp value) {
		setSysTransaction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord value9(java.lang.Object value) {
		setSysPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistoryRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3, java.lang.String value4, java.lang.String value5, java.sql.Timestamp value6, java.lang.String value7, java.sql.Timestamp value8, java.lang.Object value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ParticipationHistoryRecord
	 */
	public ParticipationHistoryRecord() {
		super(com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY);
	}

	/**
	 * Create a detached, initialised ParticipationHistoryRecord
	 */
	public ParticipationHistoryRecord(java.util.UUID id, java.util.UUID eventContext, java.util.UUID performer, java.lang.String function, java.lang.String mode, java.sql.Timestamp startTime, java.lang.String startTimeTzid, java.sql.Timestamp sysTransaction, java.lang.Object sysPeriod) {
		super(com.ethercis.dao.jooq.tables.ParticipationHistory.PARTICIPATION_HISTORY);

		setValue(0, id);
		setValue(1, eventContext);
		setValue(2, performer);
		setValue(3, function);
		setValue(4, mode);
		setValue(5, startTime);
		setValue(6, startTimeTzid);
		setValue(7, sysTransaction);
		setValue(8, sysPeriod);
	}
}
