/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditTrailRecord extends org.jooq.impl.UpdatableRecordImpl<com.ethercis.dao.jooq.tables.records.AuditTrailRecord> implements org.jooq.Record7<java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.lang.String, java.util.UUID> {

	private static final long serialVersionUID = 1291021944;

	/**
	 * Setter for <code>ehr.audit_trail.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.audit_trail.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.audit_trail.composition_id</code>.
	 */
	public void setCompositionId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.audit_trail.composition_id</code>.
	 */
	public java.util.UUID getCompositionId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.audit_trail.committer</code>.
	 */
	public void setCommitter(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.audit_trail.committer</code>.
	 */
	public java.util.UUID getCommitter() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>ehr.audit_trail.date_created</code>.
	 */
	public void setDateCreated(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.audit_trail.date_created</code>.
	 */
	public java.sql.Timestamp getDateCreated() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>ehr.audit_trail.party</code>.
	 */
	public void setParty(java.util.UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.audit_trail.party</code>.
	 */
	public java.util.UUID getParty() {
		return (java.util.UUID) getValue(4);
	}

	/**
	 * Setter for <code>ehr.audit_trail.serial_version</code>.
	 */
	public void setSerialVersion(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.audit_trail.serial_version</code>.
	 */
	public java.lang.String getSerialVersion() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehr.audit_trail.system_id</code>.
	 */
	public void setSystemId(java.util.UUID value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.audit_trail.system_id</code>.
	 */
	public java.util.UUID getSystemId() {
		return (java.util.UUID) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.lang.String, java.util.UUID> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.util.UUID, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.lang.String, java.util.UUID> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL.COMPOSITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL.COMMITTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL.DATE_CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field5() {
		return com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL.PARTY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL.SERIAL_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field7() {
		return com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL.SYSTEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getCompositionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getCommitter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getDateCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value5() {
		return getParty();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSerialVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value7() {
		return getSystemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditTrailRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditTrailRecord value2(java.util.UUID value) {
		setCompositionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditTrailRecord value3(java.util.UUID value) {
		setCommitter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditTrailRecord value4(java.sql.Timestamp value) {
		setDateCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditTrailRecord value5(java.util.UUID value) {
		setParty(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditTrailRecord value6(java.lang.String value) {
		setSerialVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditTrailRecord value7(java.util.UUID value) {
		setSystemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditTrailRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3, java.sql.Timestamp value4, java.util.UUID value5, java.lang.String value6, java.util.UUID value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AuditTrailRecord
	 */
	public AuditTrailRecord() {
		super(com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL);
	}

	/**
	 * Create a detached, initialised AuditTrailRecord
	 */
	public AuditTrailRecord(java.util.UUID id, java.util.UUID compositionId, java.util.UUID committer, java.sql.Timestamp dateCreated, java.util.UUID party, java.lang.String serialVersion, java.util.UUID systemId) {
		super(com.ethercis.dao.jooq.tables.AuditTrail.AUDIT_TRAIL);

		setValue(0, id);
		setValue(1, compositionId);
		setValue(2, committer);
		setValue(3, dateCreated);
		setValue(4, party);
		setValue(5, serialVersion);
		setValue(6, systemId);
	}
}
