/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompositionHistoryRecord extends org.jooq.impl.TableRecordImpl<com.ethercis.dao.jooq.tables.records.CompositionHistoryRecord> implements org.jooq.Record10<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.lang.Object> {

	private static final long serialVersionUID = 928411822;

	/**
	 * Setter for <code>ehr.composition_history.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.composition_history.ehr_id</code>.
	 */
	public void setEhrId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.ehr_id</code>.
	 */
	public java.util.UUID getEhrId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.composition_history.in_contribution</code>.
	 */
	public void setInContribution(java.util.UUID value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.in_contribution</code>.
	 */
	public java.util.UUID getInContribution() {
		return (java.util.UUID) getValue(2);
	}

	/**
	 * Setter for <code>ehr.composition_history.active</code>.
	 */
	public void setActive(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.active</code>.
	 */
	public java.lang.Boolean getActive() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>ehr.composition_history.is_persistent</code>.
	 */
	public void setIsPersistent(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.is_persistent</code>.
	 */
	public java.lang.Boolean getIsPersistent() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>ehr.composition_history.language</code>.
	 */
	public void setLanguage(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.language</code>.
	 */
	public java.lang.String getLanguage() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehr.composition_history.territory</code>.
	 */
	public void setTerritory(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.territory</code>.
	 */
	public java.lang.Integer getTerritory() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>ehr.composition_history.composer</code>.
	 */
	public void setComposer(java.util.UUID value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.composer</code>.
	 */
	public java.util.UUID getComposer() {
		return (java.util.UUID) getValue(7);
	}

	/**
	 * Setter for <code>ehr.composition_history.sys_transaction</code>.
	 */
	public void setSysTransaction(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.sys_transaction</code>.
	 */
	public java.sql.Timestamp getSysTransaction() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>ehr.composition_history.sys_period</code>.
	 */
	public void setSysPeriod(java.lang.Object value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehr.composition_history.sys_period</code>.
	 */
	public java.lang.Object getSysPeriod() {
		return (java.lang.Object) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.lang.Object> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.util.UUID, java.util.UUID, java.util.UUID, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.Integer, java.util.UUID, java.sql.Timestamp, java.lang.Object> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.EHR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field3() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.IN_CONTRIBUTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.IS_PERSISTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.LANGUAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.TERRITORY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field8() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.COMPOSER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.SYS_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field10() {
		return com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY.SYS_PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getEhrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value3() {
		return getInContribution();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getIsPersistent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLanguage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getTerritory();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value8() {
		return getComposer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getSysTransaction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value10() {
		return getSysPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value2(java.util.UUID value) {
		setEhrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value3(java.util.UUID value) {
		setInContribution(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value4(java.lang.Boolean value) {
		setActive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value5(java.lang.Boolean value) {
		setIsPersistent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value6(java.lang.String value) {
		setLanguage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value7(java.lang.Integer value) {
		setTerritory(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value8(java.util.UUID value) {
		setComposer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value9(java.sql.Timestamp value) {
		setSysTransaction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord value10(java.lang.Object value) {
		setSysPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompositionHistoryRecord values(java.util.UUID value1, java.util.UUID value2, java.util.UUID value3, java.lang.Boolean value4, java.lang.Boolean value5, java.lang.String value6, java.lang.Integer value7, java.util.UUID value8, java.sql.Timestamp value9, java.lang.Object value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CompositionHistoryRecord
	 */
	public CompositionHistoryRecord() {
		super(com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY);
	}

	/**
	 * Create a detached, initialised CompositionHistoryRecord
	 */
	public CompositionHistoryRecord(java.util.UUID id, java.util.UUID ehrId, java.util.UUID inContribution, java.lang.Boolean active, java.lang.Boolean isPersistent, java.lang.String language, java.lang.Integer territory, java.util.UUID composer, java.sql.Timestamp sysTransaction, java.lang.Object sysPeriod) {
		super(com.ethercis.dao.jooq.tables.CompositionHistory.COMPOSITION_HISTORY);

		setValue(0, id);
		setValue(1, ehrId);
		setValue(2, inContribution);
		setValue(3, active);
		setValue(4, isPersistent);
		setValue(5, language);
		setValue(6, territory);
		setValue(7, composer);
		setValue(8, sysTransaction);
		setValue(9, sysPeriod);
	}
}
