/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributionHistoryRecord extends org.jooq.impl.TableRecordImpl<com.ethercis.dao.jooq.tables.records.ContributionHistoryRecord> implements org.jooq.Record12<java.util.UUID, java.util.UUID, com.ethercis.dao.jooq.enums.ContributionDataType, com.ethercis.dao.jooq.enums.ContributionState, java.lang.String, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.lang.String, java.sql.Timestamp, java.lang.Object> {

	private static final long serialVersionUID = -1042301236;

	/**
	 * Setter for <code>ehr.contribution_history.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.contribution_history.ehr_id</code>.
	 */
	public void setEhrId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.ehr_id</code>.
	 */
	public java.util.UUID getEhrId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.contribution_history.contribution_type</code>.
	 */
	public void setContributionType(com.ethercis.dao.jooq.enums.ContributionDataType value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.contribution_type</code>.
	 */
	public com.ethercis.dao.jooq.enums.ContributionDataType getContributionType() {
		return (com.ethercis.dao.jooq.enums.ContributionDataType) getValue(2);
	}

	/**
	 * Setter for <code>ehr.contribution_history.state</code>.
	 */
	public void setState(com.ethercis.dao.jooq.enums.ContributionState value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.state</code>.
	 */
	public com.ethercis.dao.jooq.enums.ContributionState getState() {
		return (com.ethercis.dao.jooq.enums.ContributionState) getValue(3);
	}

	/**
	 * Setter for <code>ehr.contribution_history.signature</code>.
	 */
	public void setSignature(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.signature</code>.
	 */
	public java.lang.String getSignature() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>ehr.contribution_history.system_id</code>.
	 */
	public void setSystemId(java.util.UUID value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.system_id</code>.
	 */
	public java.util.UUID getSystemId() {
		return (java.util.UUID) getValue(5);
	}

	/**
	 * Setter for <code>ehr.contribution_history.committer</code>.
	 */
	public void setCommitter(java.util.UUID value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.committer</code>.
	 */
	public java.util.UUID getCommitter() {
		return (java.util.UUID) getValue(6);
	}

	/**
	 * Setter for <code>ehr.contribution_history.time_committed</code>.
	 */
	public void setTimeCommitted(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.time_committed</code>.
	 */
	public java.sql.Timestamp getTimeCommitted() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>ehr.contribution_history.change_type</code>.
	 */
	public void setChangeType(java.util.UUID value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.change_type</code>.
	 */
	public java.util.UUID getChangeType() {
		return (java.util.UUID) getValue(8);
	}

	/**
	 * Setter for <code>ehr.contribution_history.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>ehr.contribution_history.sys_transaction</code>.
	 */
	public void setSysTransaction(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.sys_transaction</code>.
	 */
	public java.sql.Timestamp getSysTransaction() {
		return (java.sql.Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>ehr.contribution_history.sys_period</code>.
	 */
	public void setSysPeriod(java.lang.Object value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>ehr.contribution_history.sys_period</code>.
	 */
	public java.lang.Object getSysPeriod() {
		return (java.lang.Object) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.util.UUID, java.util.UUID, com.ethercis.dao.jooq.enums.ContributionDataType, com.ethercis.dao.jooq.enums.ContributionState, java.lang.String, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.lang.String, java.sql.Timestamp, java.lang.Object> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.util.UUID, java.util.UUID, com.ethercis.dao.jooq.enums.ContributionDataType, com.ethercis.dao.jooq.enums.ContributionState, java.lang.String, java.util.UUID, java.util.UUID, java.sql.Timestamp, java.util.UUID, java.lang.String, java.sql.Timestamp, java.lang.Object> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.EHR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.ethercis.dao.jooq.enums.ContributionDataType> field3() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.CONTRIBUTION_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.ethercis.dao.jooq.enums.ContributionState> field4() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.SIGNATURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field6() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.SYSTEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field7() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.COMMITTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.TIME_COMMITTED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field9() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.CHANGE_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.SYS_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field12() {
		return com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY.SYS_PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getEhrId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.enums.ContributionDataType value3() {
		return getContributionType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ethercis.dao.jooq.enums.ContributionState value4() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSignature();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value6() {
		return getSystemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value7() {
		return getCommitter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getTimeCommitted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value9() {
		return getChangeType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getSysTransaction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value12() {
		return getSysPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value2(java.util.UUID value) {
		setEhrId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value3(com.ethercis.dao.jooq.enums.ContributionDataType value) {
		setContributionType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value4(com.ethercis.dao.jooq.enums.ContributionState value) {
		setState(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value5(java.lang.String value) {
		setSignature(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value6(java.util.UUID value) {
		setSystemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value7(java.util.UUID value) {
		setCommitter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value8(java.sql.Timestamp value) {
		setTimeCommitted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value9(java.util.UUID value) {
		setChangeType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value10(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value11(java.sql.Timestamp value) {
		setSysTransaction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord value12(java.lang.Object value) {
		setSysPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistoryRecord values(java.util.UUID value1, java.util.UUID value2, com.ethercis.dao.jooq.enums.ContributionDataType value3, com.ethercis.dao.jooq.enums.ContributionState value4, java.lang.String value5, java.util.UUID value6, java.util.UUID value7, java.sql.Timestamp value8, java.util.UUID value9, java.lang.String value10, java.sql.Timestamp value11, java.lang.Object value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ContributionHistoryRecord
	 */
	public ContributionHistoryRecord() {
		super(com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY);
	}

	/**
	 * Create a detached, initialised ContributionHistoryRecord
	 */
	public ContributionHistoryRecord(java.util.UUID id, java.util.UUID ehrId, com.ethercis.dao.jooq.enums.ContributionDataType contributionType, com.ethercis.dao.jooq.enums.ContributionState state, java.lang.String signature, java.util.UUID systemId, java.util.UUID committer, java.sql.Timestamp timeCommitted, java.util.UUID changeType, java.lang.String description, java.sql.Timestamp sysTransaction, java.lang.Object sysPeriod) {
		super(com.ethercis.dao.jooq.tables.ContributionHistory.CONTRIBUTION_HISTORY);

		setValue(0, id);
		setValue(1, ehrId);
		setValue(2, contributionType);
		setValue(3, state);
		setValue(4, signature);
		setValue(5, systemId);
		setValue(6, committer);
		setValue(7, timeCommitted);
		setValue(8, changeType);
		setValue(9, description);
		setValue(10, sysTransaction);
		setValue(11, sysPeriod);
	}
}
