/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventContextHistoryRecord extends org.jooq.impl.TableRecordImpl<com.ethercis.dao.jooq.tables.records.EventContextHistoryRecord> implements org.jooq.Record10<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.util.UUID, java.lang.String, java.lang.Object, java.util.UUID, java.sql.Timestamp, java.lang.Object> {

	private static final long serialVersionUID = -1530735700;

	/**
	 * Setter for <code>ehr.event_context_history.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>ehr.event_context_history.composition_id</code>.
	 */
	public void setCompositionId(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.composition_id</code>.
	 */
	public java.util.UUID getCompositionId() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>ehr.event_context_history.start_time</code>.
	 */
	public void setStartTime(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.start_time</code>.
	 */
	public java.sql.Timestamp getStartTime() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>ehr.event_context_history.end_time</code>.
	 */
	public void setEndTime(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.end_time</code>.
	 */
	public java.sql.Timestamp getEndTime() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>ehr.event_context_history.facility</code>.
	 */
	public void setFacility(java.util.UUID value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.facility</code>.
	 */
	public java.util.UUID getFacility() {
		return (java.util.UUID) getValue(4);
	}

	/**
	 * Setter for <code>ehr.event_context_history.location</code>.
	 */
	public void setLocation(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.location</code>.
	 */
	public java.lang.String getLocation() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>ehr.event_context_history.other_context</code>.
	 */
	public void setOtherContext(java.lang.Object value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.other_context</code>.
	 */
	public java.lang.Object getOtherContext() {
		return (java.lang.Object) getValue(6);
	}

	/**
	 * Setter for <code>ehr.event_context_history.setting</code>.
	 */
	public void setSetting(java.util.UUID value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.setting</code>.
	 */
	public java.util.UUID getSetting() {
		return (java.util.UUID) getValue(7);
	}

	/**
	 * Setter for <code>ehr.event_context_history.sys_transaction</code>.
	 */
	public void setSysTransaction(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.sys_transaction</code>.
	 */
	public java.sql.Timestamp getSysTransaction() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>ehr.event_context_history.sys_period</code>.
	 */
	public void setSysPeriod(java.lang.Object value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>ehr.event_context_history.sys_period</code>.
	 */
	public java.lang.Object getSysPeriod() {
		return (java.lang.Object) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.util.UUID, java.lang.String, java.lang.Object, java.util.UUID, java.sql.Timestamp, java.lang.Object> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.util.UUID, java.util.UUID, java.sql.Timestamp, java.sql.Timestamp, java.util.UUID, java.lang.String, java.lang.Object, java.util.UUID, java.sql.Timestamp, java.lang.Object> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.COMPOSITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.END_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field5() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.FACILITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field7() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.OTHER_CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field8() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.SETTING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.SYS_TRANSACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field10() {
		return com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY.SYS_PERIOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getCompositionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getEndTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value5() {
		return getFacility();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value7() {
		return getOtherContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value8() {
		return getSetting();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getSysTransaction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value10() {
		return getSysPeriod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value2(java.util.UUID value) {
		setCompositionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value3(java.sql.Timestamp value) {
		setStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value4(java.sql.Timestamp value) {
		setEndTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value5(java.util.UUID value) {
		setFacility(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value6(java.lang.String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value7(java.lang.Object value) {
		setOtherContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value8(java.util.UUID value) {
		setSetting(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value9(java.sql.Timestamp value) {
		setSysTransaction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord value10(java.lang.Object value) {
		setSysPeriod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EventContextHistoryRecord values(java.util.UUID value1, java.util.UUID value2, java.sql.Timestamp value3, java.sql.Timestamp value4, java.util.UUID value5, java.lang.String value6, java.lang.Object value7, java.util.UUID value8, java.sql.Timestamp value9, java.lang.Object value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EventContextHistoryRecord
	 */
	public EventContextHistoryRecord() {
		super(com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY);
	}

	/**
	 * Create a detached, initialised EventContextHistoryRecord
	 */
	public EventContextHistoryRecord(java.util.UUID id, java.util.UUID compositionId, java.sql.Timestamp startTime, java.sql.Timestamp endTime, java.util.UUID facility, java.lang.String location, java.lang.Object otherContext, java.util.UUID setting, java.sql.Timestamp sysTransaction, java.lang.Object sysPeriod) {
		super(com.ethercis.dao.jooq.tables.EventContextHistory.EVENT_CONTEXT_HISTORY);

		setValue(0, id);
		setValue(1, compositionId);
		setValue(2, startTime);
		setValue(3, endTime);
		setValue(4, facility);
		setValue(5, location);
		setValue(6, otherContext);
		setValue(7, setting);
		setValue(8, sysTransaction);
		setValue(9, sysPeriod);
	}
}
