/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq.tables.records;

/**
 * ISO 3166-1 countries codeset
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TerritoryRecord extends org.jooq.impl.UpdatableRecordImpl<com.ethercis.dao.jooq.tables.records.TerritoryRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 714552477;

	/**
	 * Setter for <code>ehr.territory.code</code>.
	 */
	public void setCode(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>ehr.territory.code</code>.
	 */
	public java.lang.Integer getCode() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>ehr.territory.twoletter</code>.
	 */
	public void setTwoletter(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>ehr.territory.twoletter</code>.
	 */
	public java.lang.String getTwoletter() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>ehr.territory.threeletter</code>.
	 */
	public void setThreeletter(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>ehr.territory.threeletter</code>.
	 */
	public java.lang.String getThreeletter() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>ehr.territory.text</code>.
	 */
	public void setText(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>ehr.territory.text</code>.
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.ethercis.dao.jooq.tables.Territory.TERRITORY.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ethercis.dao.jooq.tables.Territory.TERRITORY.TWOLETTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ethercis.dao.jooq.tables.Territory.TERRITORY.THREELETTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ethercis.dao.jooq.tables.Territory.TERRITORY.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTwoletter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getThreeletter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TerritoryRecord value1(java.lang.Integer value) {
		setCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TerritoryRecord value2(java.lang.String value) {
		setTwoletter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TerritoryRecord value3(java.lang.String value) {
		setThreeletter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TerritoryRecord value4(java.lang.String value) {
		setText(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TerritoryRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TerritoryRecord
	 */
	public TerritoryRecord() {
		super(com.ethercis.dao.jooq.tables.Territory.TERRITORY);
	}

	/**
	 * Create a detached, initialised TerritoryRecord
	 */
	public TerritoryRecord(java.lang.Integer code, java.lang.String twoletter, java.lang.String threeletter, java.lang.String text) {
		super(com.ethercis.dao.jooq.tables.Territory.TERRITORY);

		setValue(0, code);
		setValue(1, twoletter);
		setValue(2, threeletter);
		setValue(3, text);
	}
}
