/**
 * This class is generated by jOOQ
 */
package com.ethercis.dao.jooq;

/**
 * A class modelling foreign key relationships between tables of the <code>ehr</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AccessRecord> ACCESS_PKEY = UniqueKeys0.ACCESS_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AttestationRecord> ATTESTATION_PKEY = UniqueKeys0.ATTESTATION_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AttestedViewRecord> ATTESTED_VIEW_PKEY = UniqueKeys0.ATTESTED_VIEW_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.CompositionRecord> COMPOSITION_PKEY = UniqueKeys0.COMPOSITION_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ConceptRecord> CONCEPT_PKEY = UniqueKeys0.CONCEPT_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ContributionRecord> CONTRIBUTION_PKEY = UniqueKeys0.CONTRIBUTION_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EhrRecord> EHR_PKEY = UniqueKeys0.EHR_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EntryRecord> ENTRY_PKEY = UniqueKeys0.ENTRY_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EventContextRecord> EVENT_CONTEXT_PKEY = UniqueKeys0.EVENT_CONTEXT_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.LanguageRecord> LANGUAGE_PKEY = UniqueKeys0.LANGUAGE_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ParticipationRecord> PARTICIPATION_PKEY = UniqueKeys0.PARTICIPATION_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> PARTY_IDENTIFIED_PKEY = UniqueKeys0.PARTY_IDENTIFIED_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.StatusRecord> STATUS_PKEY = UniqueKeys0.STATUS_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.SystemRecord> SYSTEM_PKEY = UniqueKeys0.SYSTEM_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord> TERMINOLOGY_PROVIDER_PKEY = UniqueKeys0.TERMINOLOGY_PROVIDER_PKEY;
	public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.TerritoryRecord> TERRITORY_PKEY = UniqueKeys0.TERRITORY_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.AttestationRecord, com.ethercis.dao.jooq.tables.records.ContributionRecord> ATTESTATION__ATTESTATION_CONTRIBUTION_ID_FKEY = ForeignKeys0.ATTESTATION__ATTESTATION_CONTRIBUTION_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.AttestedViewRecord, com.ethercis.dao.jooq.tables.records.AttestationRecord> ATTESTED_VIEW__ATTESTED_VIEW_ATTESTATION_ID_FKEY = ForeignKeys0.ATTESTED_VIEW__ATTESTED_VIEW_ATTESTATION_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.EhrRecord> COMPOSITION__COMPOSITION_EHR_ID_FKEY = ForeignKeys0.COMPOSITION__COMPOSITION_EHR_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.ContributionRecord> COMPOSITION__COMPOSITION_IN_CONTRIBUTION_FKEY = ForeignKeys0.COMPOSITION__COMPOSITION_IN_CONTRIBUTION_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.LanguageRecord> COMPOSITION__COMPOSITION_LANGUAGE_FKEY = ForeignKeys0.COMPOSITION__COMPOSITION_LANGUAGE_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.TerritoryRecord> COMPOSITION__COMPOSITION_TERRITORY_FKEY = ForeignKeys0.COMPOSITION__COMPOSITION_TERRITORY_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> COMPOSITION__COMPOSITION_COMPOSER_FKEY = ForeignKeys0.COMPOSITION__COMPOSITION_COMPOSER_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ConceptRecord, com.ethercis.dao.jooq.tables.records.LanguageRecord> CONCEPT__CONCEPT_LANGUAGE_FKEY = ForeignKeys0.CONCEPT__CONCEPT_LANGUAGE_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ContributionRecord, com.ethercis.dao.jooq.tables.records.EhrRecord> CONTRIBUTION__CONTRIBUTION_EHR_ID_FKEY = ForeignKeys0.CONTRIBUTION__CONTRIBUTION_EHR_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ContributionRecord, com.ethercis.dao.jooq.tables.records.SystemRecord> CONTRIBUTION__CONTRIBUTION_SYSTEM_ID_FKEY = ForeignKeys0.CONTRIBUTION__CONTRIBUTION_SYSTEM_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ContributionRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> CONTRIBUTION__CONTRIBUTION_COMMITTER_FKEY = ForeignKeys0.CONTRIBUTION__CONTRIBUTION_COMMITTER_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EhrRecord, com.ethercis.dao.jooq.tables.records.AccessRecord> EHR__EHR_ACCESS_FKEY = ForeignKeys0.EHR__EHR_ACCESS_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EhrRecord, com.ethercis.dao.jooq.tables.records.SystemRecord> EHR__EHR_SYSTEM_ID_FKEY = ForeignKeys0.EHR__EHR_SYSTEM_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EntryRecord, com.ethercis.dao.jooq.tables.records.CompositionRecord> ENTRY__ENTRY_COMPOSITION_ID_FKEY = ForeignKeys0.ENTRY__ENTRY_COMPOSITION_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EntryRecord, com.ethercis.dao.jooq.tables.records.ConceptRecord> ENTRY__ENTRY_CATEGORY_FKEY = ForeignKeys0.ENTRY__ENTRY_CATEGORY_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EventContextRecord, com.ethercis.dao.jooq.tables.records.CompositionRecord> EVENT_CONTEXT__EVENT_CONTEXT_COMPOSITION_ID_FKEY = ForeignKeys0.EVENT_CONTEXT__EVENT_CONTEXT_COMPOSITION_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EventContextRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> EVENT_CONTEXT__EVENT_CONTEXT_FACILITY_FKEY = ForeignKeys0.EVENT_CONTEXT__EVENT_CONTEXT_FACILITY_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EventContextRecord, com.ethercis.dao.jooq.tables.records.ConceptRecord> EVENT_CONTEXT__EVENT_CONTEXT_SETTING_FKEY = ForeignKeys0.EVENT_CONTEXT__EVENT_CONTEXT_SETTING_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.IdentifierRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> IDENTIFIER__IDENTIFIER_PARTY_FKEY = ForeignKeys0.IDENTIFIER__IDENTIFIER_PARTY_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ParticipationRecord, com.ethercis.dao.jooq.tables.records.EventContextRecord> PARTICIPATION__PARTICIPATION_EVENT_CONTEXT_FKEY = ForeignKeys0.PARTICIPATION__PARTICIPATION_EVENT_CONTEXT_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ParticipationRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> PARTICIPATION__PARTICIPATION_PERFORMER_FKEY = ForeignKeys0.PARTICIPATION__PARTICIPATION_PERFORMER_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.StatusRecord, com.ethercis.dao.jooq.tables.records.EhrRecord> STATUS__STATUS_EHR_ID_FKEY = ForeignKeys0.STATUS__STATUS_EHR_ID_FKEY;
	public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.StatusRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> STATUS__STATUS_PARTY_FKEY = ForeignKeys0.STATUS__STATUS_PARTY_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AccessRecord> ACCESS_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Access.ACCESS, com.ethercis.dao.jooq.tables.Access.ACCESS.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AttestationRecord> ATTESTATION_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Attestation.ATTESTATION, com.ethercis.dao.jooq.tables.Attestation.ATTESTATION.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.AttestedViewRecord> ATTESTED_VIEW_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW, com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.CompositionRecord> COMPOSITION_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Composition.COMPOSITION, com.ethercis.dao.jooq.tables.Composition.COMPOSITION.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ConceptRecord> CONCEPT_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Concept.CONCEPT, com.ethercis.dao.jooq.tables.Concept.CONCEPT.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ContributionRecord> CONTRIBUTION_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION, com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EhrRecord> EHR_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Ehr.EHR, com.ethercis.dao.jooq.tables.Ehr.EHR.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EntryRecord> ENTRY_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Entry.ENTRY, com.ethercis.dao.jooq.tables.Entry.ENTRY.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.EventContextRecord> EVENT_CONTEXT_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.EventContext.EVENT_CONTEXT, com.ethercis.dao.jooq.tables.EventContext.EVENT_CONTEXT.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.LanguageRecord> LANGUAGE_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Language.LANGUAGE, com.ethercis.dao.jooq.tables.Language.LANGUAGE.CODE);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.ParticipationRecord> PARTICIPATION_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Participation.PARTICIPATION, com.ethercis.dao.jooq.tables.Participation.PARTICIPATION.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> PARTY_IDENTIFIED_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED, com.ethercis.dao.jooq.tables.PartyIdentified.PARTY_IDENTIFIED.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.StatusRecord> STATUS_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Status.STATUS, com.ethercis.dao.jooq.tables.Status.STATUS.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.SystemRecord> SYSTEM_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.System.SYSTEM, com.ethercis.dao.jooq.tables.System.SYSTEM.ID);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.TerminologyProviderRecord> TERMINOLOGY_PROVIDER_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.TerminologyProvider.TERMINOLOGY_PROVIDER, com.ethercis.dao.jooq.tables.TerminologyProvider.TERMINOLOGY_PROVIDER.CODE);
		public static final org.jooq.UniqueKey<com.ethercis.dao.jooq.tables.records.TerritoryRecord> TERRITORY_PKEY = createUniqueKey(com.ethercis.dao.jooq.tables.Territory.TERRITORY, com.ethercis.dao.jooq.tables.Territory.TERRITORY.CODE);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.AttestationRecord, com.ethercis.dao.jooq.tables.records.ContributionRecord> ATTESTATION__ATTESTATION_CONTRIBUTION_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.CONTRIBUTION_PKEY, com.ethercis.dao.jooq.tables.Attestation.ATTESTATION, com.ethercis.dao.jooq.tables.Attestation.ATTESTATION.CONTRIBUTION_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.AttestedViewRecord, com.ethercis.dao.jooq.tables.records.AttestationRecord> ATTESTED_VIEW__ATTESTED_VIEW_ATTESTATION_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.ATTESTATION_PKEY, com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW, com.ethercis.dao.jooq.tables.AttestedView.ATTESTED_VIEW.ATTESTATION_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.EhrRecord> COMPOSITION__COMPOSITION_EHR_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.EHR_PKEY, com.ethercis.dao.jooq.tables.Composition.COMPOSITION, com.ethercis.dao.jooq.tables.Composition.COMPOSITION.EHR_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.ContributionRecord> COMPOSITION__COMPOSITION_IN_CONTRIBUTION_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.CONTRIBUTION_PKEY, com.ethercis.dao.jooq.tables.Composition.COMPOSITION, com.ethercis.dao.jooq.tables.Composition.COMPOSITION.IN_CONTRIBUTION);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.LanguageRecord> COMPOSITION__COMPOSITION_LANGUAGE_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.LANGUAGE_PKEY, com.ethercis.dao.jooq.tables.Composition.COMPOSITION, com.ethercis.dao.jooq.tables.Composition.COMPOSITION.LANGUAGE);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.TerritoryRecord> COMPOSITION__COMPOSITION_TERRITORY_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.TERRITORY_PKEY, com.ethercis.dao.jooq.tables.Composition.COMPOSITION, com.ethercis.dao.jooq.tables.Composition.COMPOSITION.TERRITORY);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.CompositionRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> COMPOSITION__COMPOSITION_COMPOSER_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.PARTY_IDENTIFIED_PKEY, com.ethercis.dao.jooq.tables.Composition.COMPOSITION, com.ethercis.dao.jooq.tables.Composition.COMPOSITION.COMPOSER);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ConceptRecord, com.ethercis.dao.jooq.tables.records.LanguageRecord> CONCEPT__CONCEPT_LANGUAGE_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.LANGUAGE_PKEY, com.ethercis.dao.jooq.tables.Concept.CONCEPT, com.ethercis.dao.jooq.tables.Concept.CONCEPT.LANGUAGE);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ContributionRecord, com.ethercis.dao.jooq.tables.records.EhrRecord> CONTRIBUTION__CONTRIBUTION_EHR_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.EHR_PKEY, com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION, com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.EHR_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ContributionRecord, com.ethercis.dao.jooq.tables.records.SystemRecord> CONTRIBUTION__CONTRIBUTION_SYSTEM_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.SYSTEM_PKEY, com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION, com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.SYSTEM_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ContributionRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> CONTRIBUTION__CONTRIBUTION_COMMITTER_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.PARTY_IDENTIFIED_PKEY, com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION, com.ethercis.dao.jooq.tables.Contribution.CONTRIBUTION.COMMITTER);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EhrRecord, com.ethercis.dao.jooq.tables.records.AccessRecord> EHR__EHR_ACCESS_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.ACCESS_PKEY, com.ethercis.dao.jooq.tables.Ehr.EHR, com.ethercis.dao.jooq.tables.Ehr.EHR.ACCESS);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EhrRecord, com.ethercis.dao.jooq.tables.records.SystemRecord> EHR__EHR_SYSTEM_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.SYSTEM_PKEY, com.ethercis.dao.jooq.tables.Ehr.EHR, com.ethercis.dao.jooq.tables.Ehr.EHR.SYSTEM_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EntryRecord, com.ethercis.dao.jooq.tables.records.CompositionRecord> ENTRY__ENTRY_COMPOSITION_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.COMPOSITION_PKEY, com.ethercis.dao.jooq.tables.Entry.ENTRY, com.ethercis.dao.jooq.tables.Entry.ENTRY.COMPOSITION_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EntryRecord, com.ethercis.dao.jooq.tables.records.ConceptRecord> ENTRY__ENTRY_CATEGORY_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.CONCEPT_PKEY, com.ethercis.dao.jooq.tables.Entry.ENTRY, com.ethercis.dao.jooq.tables.Entry.ENTRY.CATEGORY);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EventContextRecord, com.ethercis.dao.jooq.tables.records.CompositionRecord> EVENT_CONTEXT__EVENT_CONTEXT_COMPOSITION_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.COMPOSITION_PKEY, com.ethercis.dao.jooq.tables.EventContext.EVENT_CONTEXT, com.ethercis.dao.jooq.tables.EventContext.EVENT_CONTEXT.COMPOSITION_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EventContextRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> EVENT_CONTEXT__EVENT_CONTEXT_FACILITY_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.PARTY_IDENTIFIED_PKEY, com.ethercis.dao.jooq.tables.EventContext.EVENT_CONTEXT, com.ethercis.dao.jooq.tables.EventContext.EVENT_CONTEXT.FACILITY);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.EventContextRecord, com.ethercis.dao.jooq.tables.records.ConceptRecord> EVENT_CONTEXT__EVENT_CONTEXT_SETTING_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.CONCEPT_PKEY, com.ethercis.dao.jooq.tables.EventContext.EVENT_CONTEXT, com.ethercis.dao.jooq.tables.EventContext.EVENT_CONTEXT.SETTING);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.IdentifierRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> IDENTIFIER__IDENTIFIER_PARTY_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.PARTY_IDENTIFIED_PKEY, com.ethercis.dao.jooq.tables.Identifier.IDENTIFIER, com.ethercis.dao.jooq.tables.Identifier.IDENTIFIER.PARTY);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ParticipationRecord, com.ethercis.dao.jooq.tables.records.EventContextRecord> PARTICIPATION__PARTICIPATION_EVENT_CONTEXT_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.EVENT_CONTEXT_PKEY, com.ethercis.dao.jooq.tables.Participation.PARTICIPATION, com.ethercis.dao.jooq.tables.Participation.PARTICIPATION.EVENT_CONTEXT);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.ParticipationRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> PARTICIPATION__PARTICIPATION_PERFORMER_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.PARTY_IDENTIFIED_PKEY, com.ethercis.dao.jooq.tables.Participation.PARTICIPATION, com.ethercis.dao.jooq.tables.Participation.PARTICIPATION.PERFORMER);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.StatusRecord, com.ethercis.dao.jooq.tables.records.EhrRecord> STATUS__STATUS_EHR_ID_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.EHR_PKEY, com.ethercis.dao.jooq.tables.Status.STATUS, com.ethercis.dao.jooq.tables.Status.STATUS.EHR_ID);
		public static final org.jooq.ForeignKey<com.ethercis.dao.jooq.tables.records.StatusRecord, com.ethercis.dao.jooq.tables.records.PartyIdentifiedRecord> STATUS__STATUS_PARTY_FKEY = createForeignKey(com.ethercis.dao.jooq.Keys.PARTY_IDENTIFIED_PKEY, com.ethercis.dao.jooq.tables.Status.STATUS, com.ethercis.dao.jooq.tables.Status.STATUS.PARTY);
	}
}
