/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.tables.records.ParticipationHistoryRecord;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParticipationHistory extends TableImpl<ParticipationHistoryRecord> {

	private static final long serialVersionUID = 2121712115;

	/**
	 * The reference instance of <code>ehr.participation_history</code>
	 */
	public static final ParticipationHistory PARTICIPATION_HISTORY = new ParticipationHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ParticipationHistoryRecord> getRecordType() {
		return ParticipationHistoryRecord.class;
	}

	/**
	 * The column <code>ehr.participation_history.id</code>.
	 */
	public final TableField<ParticipationHistoryRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.participation_history.event_context</code>.
	 */
	public final TableField<ParticipationHistoryRecord, UUID> EVENT_CONTEXT = createField("event_context", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.participation_history.performer</code>.
	 */
	public final TableField<ParticipationHistoryRecord, UUID> PERFORMER = createField("performer", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.participation_history.function</code>.
	 */
	public final TableField<ParticipationHistoryRecord, String> FUNCTION = createField("function", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.participation_history.mode</code>.
	 */
	public final TableField<ParticipationHistoryRecord, String> MODE = createField("mode", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.participation_history.start_time</code>.
	 */
	public final TableField<ParticipationHistoryRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehr.participation_history.start_time_tzid</code>.
	 */
	public final TableField<ParticipationHistoryRecord, String> START_TIME_TZID = createField("start_time_tzid", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ehr.participation_history.sys_transaction</code>.
	 */
	public final TableField<ParticipationHistoryRecord, Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.participation_history.sys_period</code>.
	 */
	public final TableField<ParticipationHistoryRecord, Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.participation_history</code> table reference
	 */
	public ParticipationHistory() {
		this("participation_history", null);
	}

	/**
	 * Create an aliased <code>ehr.participation_history</code> table reference
	 */
	public ParticipationHistory(String alias) {
		this(alias, PARTICIPATION_HISTORY);
	}

	private ParticipationHistory(String alias, Table<ParticipationHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private ParticipationHistory(String alias, Table<ParticipationHistoryRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParticipationHistory as(String alias) {
		return new ParticipationHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ParticipationHistory rename(String name) {
		return new ParticipationHistory(name, null);
	}
}
