/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.tables.records.CompExpandRecord;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompExpand extends TableImpl<CompExpandRecord> {

	private static final long serialVersionUID = 71585902;

	/**
	 * The reference instance of <code>ehr.comp_expand</code>
	 */
	public static final CompExpand COMP_EXPAND = new CompExpand();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CompExpandRecord> getRecordType() {
		return CompExpandRecord.class;
	}

	/**
	 * The column <code>ehr.comp_expand.ehr_id</code>.
	 */
	public final TableField<CompExpandRecord, UUID> EHR_ID = createField("ehr_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.comp_expand.subject_externalref_id_value</code>.
	 */
	public final TableField<CompExpandRecord, String> SUBJECT_EXTERNALREF_ID_VALUE = createField("subject_externalref_id_value", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.subject_externalref_id_namespace</code>.
	 */
	public final TableField<CompExpandRecord, String> SUBJECT_EXTERNALREF_ID_NAMESPACE = createField("subject_externalref_id_namespace", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.composition_id</code>.
	 */
	public final TableField<CompExpandRecord, UUID> COMPOSITION_ID = createField("composition_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.comp_expand.template_id</code>.
	 */
	public final TableField<CompExpandRecord, String> TEMPLATE_ID = createField("template_id", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>ehr.comp_expand.archetype_id</code>.
	 */
	public final TableField<CompExpandRecord, String> ARCHETYPE_ID = createField("archetype_id", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>ehr.comp_expand.entry</code>.
	 */
	public final TableField<CompExpandRecord, Object> ENTRY = createField("entry", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>ehr.comp_expand.composition_name</code>.
	 */
	public final TableField<CompExpandRecord, String> COMPOSITION_NAME = createField("composition_name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>ehr.comp_expand.language</code>.
	 */
	public final TableField<CompExpandRecord, String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * The column <code>ehr.comp_expand.territory</code>.
	 */
	public final TableField<CompExpandRecord, Integer> TERRITORY = createField("territory", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ehr.comp_expand.start_time</code>.
	 */
	public final TableField<CompExpandRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehr.comp_expand.start_time_tzid</code>.
	 */
	public final TableField<CompExpandRecord, String> START_TIME_TZID = createField("start_time_tzid", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ehr.comp_expand.end_time</code>.
	 */
	public final TableField<CompExpandRecord, Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehr.comp_expand.end_time_tzid</code>.
	 */
	public final TableField<CompExpandRecord, String> END_TIME_TZID = createField("end_time_tzid", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ehr.comp_expand.other_context</code>.
	 */
	public final TableField<CompExpandRecord, Object> OTHER_CONTEXT = createField("other_context", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>ehr.comp_expand.ctx_location</code>.
	 */
	public final TableField<CompExpandRecord, String> CTX_LOCATION = createField("ctx_location", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.facility_name</code>.
	 */
	public final TableField<CompExpandRecord, String> FACILITY_NAME = createField("facility_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.facility_ref</code>.
	 */
	public final TableField<CompExpandRecord, String> FACILITY_REF = createField("facility_ref", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.facility_scheme</code>.
	 */
	public final TableField<CompExpandRecord, String> FACILITY_SCHEME = createField("facility_scheme", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>ehr.comp_expand.facility_namespace</code>.
	 */
	public final TableField<CompExpandRecord, String> FACILITY_NAMESPACE = createField("facility_namespace", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.facility_type</code>.
	 */
	public final TableField<CompExpandRecord, String> FACILITY_TYPE = createField("facility_type", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.composer_name</code>.
	 */
	public final TableField<CompExpandRecord, String> COMPOSER_NAME = createField("composer_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.composer_ref</code>.
	 */
	public final TableField<CompExpandRecord, String> COMPOSER_REF = createField("composer_ref", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.composer_scheme</code>.
	 */
	public final TableField<CompExpandRecord, String> COMPOSER_SCHEME = createField("composer_scheme", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>ehr.comp_expand.composer_namespace</code>.
	 */
	public final TableField<CompExpandRecord, String> COMPOSER_NAMESPACE = createField("composer_namespace", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.composer_type</code>.
	 */
	public final TableField<CompExpandRecord, String> COMPOSER_TYPE = createField("composer_type", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.comp_expand.other_details</code>.
	 */
	public final TableField<CompExpandRecord, Object> OTHER_DETAILS = createField("other_details", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * Create a <code>ehr.comp_expand</code> table reference
	 */
	public CompExpand() {
		this("comp_expand", null);
	}

	/**
	 * Create an aliased <code>ehr.comp_expand</code> table reference
	 */
	public CompExpand(String alias) {
		this(alias, COMP_EXPAND);
	}

	private CompExpand(String alias, Table<CompExpandRecord> aliased) {
		this(alias, aliased, null);
	}

	private CompExpand(String alias, Table<CompExpandRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompExpand as(String alias) {
		return new CompExpand(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CompExpand rename(String name) {
		return new CompExpand(name, null);
	}
}
