/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.Keys;
import com.ethercis.jooq.pg.enums.ContributionChangeType;
import com.ethercis.jooq.pg.enums.ContributionDataType;
import com.ethercis.jooq.pg.enums.ContributionState;
import com.ethercis.jooq.pg.tables.records.ContributionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * Contribution table, compositions reference this table
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contribution extends TableImpl<ContributionRecord> {

	private static final long serialVersionUID = 404481560;

	/**
	 * The reference instance of <code>ehr.contribution</code>
	 */
	public static final Contribution CONTRIBUTION = new Contribution();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ContributionRecord> getRecordType() {
		return ContributionRecord.class;
	}

	/**
	 * The column <code>ehr.contribution.id</code>.
	 */
	public final TableField<ContributionRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehr.contribution.ehr_id</code>.
	 */
	public final TableField<ContributionRecord, UUID> EHR_ID = createField("ehr_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution.contribution_type</code>.
	 */
	public final TableField<ContributionRecord, ContributionDataType> CONTRIBUTION_TYPE = createField("contribution_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.jooq.pg.enums.ContributionDataType.class), this, "");

	/**
	 * The column <code>ehr.contribution.state</code>.
	 */
	public final TableField<ContributionRecord, ContributionState> STATE = createField("state", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.jooq.pg.enums.ContributionState.class), this, "");

	/**
	 * The column <code>ehr.contribution.signature</code>.
	 */
	public final TableField<ContributionRecord, String> SIGNATURE = createField("signature", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>ehr.contribution.system_id</code>.
	 */
	public final TableField<ContributionRecord, UUID> SYSTEM_ID = createField("system_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution.committer</code>.
	 */
	public final TableField<ContributionRecord, UUID> COMMITTER = createField("committer", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution.time_committed</code>.
	 */
	public final TableField<ContributionRecord, Timestamp> TIME_COMMITTED = createField("time_committed", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>ehr.contribution.time_committed_tzid</code>.
	 */
	public final TableField<ContributionRecord, String> TIME_COMMITTED_TZID = createField("time_committed_tzid", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ehr.contribution.change_type</code>.
	 */
	public final TableField<ContributionRecord, ContributionChangeType> CHANGE_TYPE = createField("change_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.jooq.pg.enums.ContributionChangeType.class), this, "");

	/**
	 * The column <code>ehr.contribution.description</code>.
	 */
	public final TableField<ContributionRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>ehr.contribution.sys_transaction</code>.
	 */
	public final TableField<ContributionRecord, Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.contribution.sys_period</code>.
	 */
	public final TableField<ContributionRecord, Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.contribution</code> table reference
	 */
	public Contribution() {
		this("contribution", null);
	}

	/**
	 * Create an aliased <code>ehr.contribution</code> table reference
	 */
	public Contribution(String alias) {
		this(alias, CONTRIBUTION);
	}

	private Contribution(String alias, Table<ContributionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Contribution(String alias, Table<ContributionRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "Contribution table, compositions reference this table");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ContributionRecord> getPrimaryKey() {
		return Keys.CONTRIBUTION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ContributionRecord>> getKeys() {
		return Arrays.<UniqueKey<ContributionRecord>>asList(Keys.CONTRIBUTION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ContributionRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ContributionRecord, ?>>asList(Keys.CONTRIBUTION__CONTRIBUTION_EHR_ID_FKEY, Keys.CONTRIBUTION__CONTRIBUTION_SYSTEM_ID_FKEY, Keys.CONTRIBUTION__CONTRIBUTION_COMMITTER_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Contribution as(String alias) {
		return new Contribution(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Contribution rename(String name) {
		return new Contribution(name, null);
	}
}
