/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.enums.ContributionChangeType;
import com.ethercis.jooq.pg.enums.ContributionDataType;
import com.ethercis.jooq.pg.enums.ContributionState;
import com.ethercis.jooq.pg.tables.records.ContributionHistoryRecord;

import java.sql.Timestamp;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributionHistory extends TableImpl<ContributionHistoryRecord> {

	private static final long serialVersionUID = -1435481334;

	/**
	 * The reference instance of <code>ehr.contribution_history</code>
	 */
	public static final ContributionHistory CONTRIBUTION_HISTORY = new ContributionHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ContributionHistoryRecord> getRecordType() {
		return ContributionHistoryRecord.class;
	}

	/**
	 * The column <code>ehr.contribution_history.id</code>.
	 */
	public final TableField<ContributionHistoryRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>ehr.contribution_history.ehr_id</code>.
	 */
	public final TableField<ContributionHistoryRecord, UUID> EHR_ID = createField("ehr_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution_history.contribution_type</code>.
	 */
	public final TableField<ContributionHistoryRecord, ContributionDataType> CONTRIBUTION_TYPE = createField("contribution_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.jooq.pg.enums.ContributionDataType.class), this, "");

	/**
	 * The column <code>ehr.contribution_history.state</code>.
	 */
	public final TableField<ContributionHistoryRecord, ContributionState> STATE = createField("state", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.jooq.pg.enums.ContributionState.class), this, "");

	/**
	 * The column <code>ehr.contribution_history.signature</code>.
	 */
	public final TableField<ContributionHistoryRecord, String> SIGNATURE = createField("signature", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>ehr.contribution_history.system_id</code>.
	 */
	public final TableField<ContributionHistoryRecord, UUID> SYSTEM_ID = createField("system_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution_history.committer</code>.
	 */
	public final TableField<ContributionHistoryRecord, UUID> COMMITTER = createField("committer", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.contribution_history.time_committed</code>.
	 */
	public final TableField<ContributionHistoryRecord, Timestamp> TIME_COMMITTED = createField("time_committed", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehr.contribution_history.time_committed_tzid</code>.
	 */
	public final TableField<ContributionHistoryRecord, String> TIME_COMMITTED_TZID = createField("time_committed_tzid", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>ehr.contribution_history.change_type</code>.
	 */
	public final TableField<ContributionHistoryRecord, ContributionChangeType> CHANGE_TYPE = createField("change_type", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.ethercis.jooq.pg.enums.ContributionChangeType.class), this, "");

	/**
	 * The column <code>ehr.contribution_history.description</code>.
	 */
	public final TableField<ContributionHistoryRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>ehr.contribution_history.sys_transaction</code>.
	 */
	public final TableField<ContributionHistoryRecord, Timestamp> SYS_TRANSACTION = createField("sys_transaction", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>ehr.contribution_history.sys_period</code>.
	 */
	public final TableField<ContributionHistoryRecord, Object> SYS_PERIOD = createField("sys_period", org.jooq.impl.DefaultDataType.getDefaultDataType("tstzrange"), this, "");

	/**
	 * Create a <code>ehr.contribution_history</code> table reference
	 */
	public ContributionHistory() {
		this("contribution_history", null);
	}

	/**
	 * Create an aliased <code>ehr.contribution_history</code> table reference
	 */
	public ContributionHistory(String alias) {
		this(alias, CONTRIBUTION_HISTORY);
	}

	private ContributionHistory(String alias, Table<ContributionHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private ContributionHistory(String alias, Table<ContributionHistoryRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ContributionHistory as(String alias) {
		return new ContributionHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ContributionHistory rename(String name) {
		return new ContributionHistory(name, null);
	}
}
