/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.Keys;
import com.ethercis.jooq.pg.tables.records.HeadingRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Heading extends TableImpl<HeadingRecord> {

	private static final long serialVersionUID = 1224321284;

	/**
	 * The reference instance of <code>ehr.heading</code>
	 */
	public static final Heading HEADING = new Heading();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<HeadingRecord> getRecordType() {
		return HeadingRecord.class;
	}

	/**
	 * The column <code>ehr.heading.code</code>.
	 */
	public final TableField<HeadingRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(16).nullable(false), this, "");

	/**
	 * The column <code>ehr.heading.name</code>.
	 */
	public final TableField<HeadingRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>ehr.heading.description</code>.
	 */
	public final TableField<HeadingRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>ehr.heading</code> table reference
	 */
	public Heading() {
		this("heading", null);
	}

	/**
	 * Create an aliased <code>ehr.heading</code> table reference
	 */
	public Heading(String alias) {
		this(alias, HEADING);
	}

	private Heading(String alias, Table<HeadingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Heading(String alias, Table<HeadingRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<HeadingRecord> getPrimaryKey() {
		return Keys.HEADING_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<HeadingRecord>> getKeys() {
		return Arrays.<UniqueKey<HeadingRecord>>asList(Keys.HEADING_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Heading as(String alias) {
		return new Heading(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Heading rename(String name) {
		return new Heading(name, null);
	}
}
