/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.Keys;
import com.ethercis.jooq.pg.tables.records.SessionLogRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionLog extends TableImpl<SessionLogRecord> {

	private static final long serialVersionUID = 1640652544;

	/**
	 * The reference instance of <code>ehr.session_log</code>
	 */
	public static final SessionLog SESSION_LOG = new SessionLog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SessionLogRecord> getRecordType() {
		return SessionLogRecord.class;
	}

	/**
	 * The column <code>ehr.session_log.id</code>.
	 */
	public final TableField<SessionLogRecord, UUID> ID = createField("id", org.jooq.impl.SQLDataType.UUID.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ehr.session_log.subject_id</code>.
	 */
	public final TableField<SessionLogRecord, String> SUBJECT_ID = createField("subject_id", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>ehr.session_log.node_id</code>.
	 */
	public final TableField<SessionLogRecord, String> NODE_ID = createField("node_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>ehr.session_log.session_id</code>.
	 */
	public final TableField<SessionLogRecord, String> SESSION_ID = createField("session_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>ehr.session_log.session_name</code>.
	 */
	public final TableField<SessionLogRecord, String> SESSION_NAME = createField("session_name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>ehr.session_log.session_time</code>.
	 */
	public final TableField<SessionLogRecord, Timestamp> SESSION_TIME = createField("session_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>ehr.session_log.ip_address</code>.
	 */
	public final TableField<SessionLogRecord, String> IP_ADDRESS = createField("ip_address", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>ehr.session_log</code> table reference
	 */
	public SessionLog() {
		this("session_log", null);
	}

	/**
	 * Create an aliased <code>ehr.session_log</code> table reference
	 */
	public SessionLog(String alias) {
		this(alias, SESSION_LOG);
	}

	private SessionLog(String alias, Table<SessionLogRecord> aliased) {
		this(alias, aliased, null);
	}

	private SessionLog(String alias, Table<SessionLogRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SessionLogRecord> getPrimaryKey() {
		return Keys.SESSION_LOG_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SessionLogRecord>> getKeys() {
		return Arrays.<UniqueKey<SessionLogRecord>>asList(Keys.SESSION_LOG_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SessionLog as(String alias) {
		return new SessionLog(alias, this);
	}

	/**
	 * Rename this table
	 */
	public SessionLog rename(String name) {
		return new SessionLog(name, null);
	}
}
