/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.tables.records.StatusDetailsRecord;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusDetails extends TableImpl<StatusDetailsRecord> {

	private static final long serialVersionUID = 1598632412;

	/**
	 * The reference instance of <code>ehr.status_details</code>
	 */
	public static final StatusDetails STATUS_DETAILS = new StatusDetails();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<StatusDetailsRecord> getRecordType() {
		return StatusDetailsRecord.class;
	}

	/**
	 * The column <code>ehr.status_details.ehr_id</code>.
	 */
	public final TableField<StatusDetailsRecord, UUID> EHR_ID = createField("ehr_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>ehr.status_details.is_modifiable</code>.
	 */
	public final TableField<StatusDetailsRecord, Boolean> IS_MODIFIABLE = createField("is_modifiable", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>ehr.status_details.is_queryable</code>.
	 */
	public final TableField<StatusDetailsRecord, Boolean> IS_QUERYABLE = createField("is_queryable", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>ehr.status_details.other_details</code>.
	 */
	public final TableField<StatusDetailsRecord, Object> OTHER_DETAILS = createField("other_details", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "");

	/**
	 * The column <code>ehr.status_details.party_name</code>.
	 */
	public final TableField<StatusDetailsRecord, String> PARTY_NAME = createField("party_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.status_details.party_ref_namespace</code>.
	 */
	public final TableField<StatusDetailsRecord, String> PARTY_REF_NAMESPACE = createField("party_ref_namespace", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>ehr.status_details.party_ref_scheme</code>.
	 */
	public final TableField<StatusDetailsRecord, String> PARTY_REF_SCHEME = createField("party_ref_scheme", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>ehr.status_details.party_ref_type</code>.
	 */
	public final TableField<StatusDetailsRecord, String> PARTY_REF_TYPE = createField("party_ref_type", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>ehr.status_details</code> table reference
	 */
	public StatusDetails() {
		this("status_details", null);
	}

	/**
	 * Create an aliased <code>ehr.status_details</code> table reference
	 */
	public StatusDetails(String alias) {
		this(alias, STATUS_DETAILS);
	}

	private StatusDetails(String alias, Table<StatusDetailsRecord> aliased) {
		this(alias, aliased, null);
	}

	private StatusDetails(String alias, Table<StatusDetailsRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public StatusDetails as(String alias) {
		return new StatusDetails(alias, this);
	}

	/**
	 * Rename this table
	 */
	public StatusDetails rename(String name) {
		return new StatusDetails(name, null);
	}
}
