/**
 * This class is generated by jOOQ
 */
package com.ethercis.jooq.pg.tables;


import com.ethercis.jooq.pg.Ehr;
import com.ethercis.jooq.pg.tables.records.TemplateMetaRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TemplateMeta extends TableImpl<TemplateMetaRecord> {

	private static final long serialVersionUID = 1926849144;

	/**
	 * The reference instance of <code>ehr.template_meta</code>
	 */
	public static final TemplateMeta TEMPLATE_META = new TemplateMeta();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TemplateMetaRecord> getRecordType() {
		return TemplateMetaRecord.class;
	}

	/**
	 * The column <code>ehr.template_meta.template_id</code>.
	 */
	public final TableField<TemplateMetaRecord, String> TEMPLATE_ID = createField("template_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>ehr.template_meta.array_path</code>.
	 */
	public final TableField<TemplateMetaRecord, String[]> ARRAY_PATH = createField("array_path", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

	/**
	 * Create a <code>ehr.template_meta</code> table reference
	 */
	public TemplateMeta() {
		this("template_meta", null);
	}

	/**
	 * Create an aliased <code>ehr.template_meta</code> table reference
	 */
	public TemplateMeta(String alias) {
		this(alias, TEMPLATE_META);
	}

	private TemplateMeta(String alias, Table<TemplateMetaRecord> aliased) {
		this(alias, aliased, null);
	}

	private TemplateMeta(String alias, Table<TemplateMetaRecord> aliased, Field<?>[] parameters) {
		super(alias, Ehr.EHR, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TemplateMeta as(String alias) {
		return new TemplateMeta(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TemplateMeta rename(String name) {
		return new TemplateMeta(name, null);
	}
}
